# Etape 1 - Importation des librairies et chargement des fichiers

## 1.1 - Importation des librairies et paramétrage

In [ ]:
#Importation de la librairie Pandas
import pandas as pd

#Importation de la librairie NumPy
import numpy as np

#Afficher toutes les colonnes d'un dataframe et monter le maximum de lignes affichées à 100
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

## 1.2 - Chargement des fichiers

In [ ]:
#Connecter au Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Importation des données FAO
df_fao_dispo = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/FAOSTAT_Dispo_2010_2023.csv', sep=',')
df_fao_healthydiet = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/FAOSTAT_healthy_diet_2017_2024.csv', sep=',')
df_fao_PIB = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/FAOSTAT_PIB_2010_2024.csv', sep=',')
df_fao_population = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/FAOSTAT_Population_2010_2023.csv', sep=',')
df_fao_stability = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/FAOSTAT_Stabilité_2010_2024.csv', sep=',')

#importation des données de WBG
df_wbg_index = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/WBG_Indices.csv', sep=',')
df_wbg_temperature = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/WBG_Temperature.csv', sep=',')

#importation des données de CEPII
df_cepii_distance = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/CEPII_distances.csv', sep=';')
df_cepii_langue = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data P11/CEPII_langues.csv', sep=';')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Etape 2 - Analyse exploratoire des fichiers

## 2.1 - Analyse exploratoire df_fao_dispo

### 2.1.1 - Evalutation du dataset

In [ ]:
#Caractéristiques
df_fao_dispo.info()
print("\n")
df_fao_dispo.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9662 entries, 0 to 9661
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            9662 non-null   object
 1   Domaine                 9662 non-null   object
 2   Code zone (M49)         9662 non-null   int64
 3   Zone                    9662 non-null   object
 4   Code Élément            9662 non-null   int64
 5   Élément                 9662 non-null   object
 6   Code Produit (FBS)      9662 non-null   object
 7   Produit                 9662 non-null   object
 8   Code année              9662 non-null   int64
 9   Année                   9662 non-null   int64
 10  Unité                   9662 non-null   object
 11  Valeur                  9662 non-null   float64
 12  Symbole                 9662 non-null   object
 13  Description du Symbole  9662 non-null   object
 14  Note                    0 non-null      float64
dtypes: float64(2), int64(4), object(9)
memory usage: 1.1+ MB

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (FBS),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
count,9662,9662,9662.000000,9662,9662.000000,9662,9662,9662,9662.000000,9662.000000,9662,9662.000000,9662,9662,0.0
unique,1,1,NaN,179,NaN,4,1,1,NaN,NaN,2,NaN,2,2,NaN
top,FBS,Bilans Alimentaires (2010-),NaN,Afghanistan,NaN,Disponibilité alimentaire en quantité (kg/pers...,S2734,Viande de Volailles,NaN,NaN,1000 t,NaN,I,Valeur imputée par une agence réceptrice,NaN
freq,9662,9662,NaN,56,NaN,2425,9662,9662,NaN,NaN,7237,NaN,7195,7195,NaN
mean,NaN,NaN,431.307390,NaN,4262.055682,NaN,NaN,NaN,2016.556614,2016.556614,NaN,430.364351,NaN,NaN,NaN
std,NaN,NaN,251.780133,NaN,2096.887250,NaN,NaN,NaN,4.038969,4.038969,NaN,2032.327989,NaN,NaN,NaN
min,NaN,NaN,4.000000,NaN,645.000000,NaN,NaN,NaN,2010.000000,2010.000000,NaN,0.000000,NaN,NaN,NaN
25%,NaN,NaN,214.000000,NaN,645.000000,NaN,NaN,NaN,2013.000000,2013.000000,NaN,9.457500,NaN,NaN,NaN
50%,NaN,NaN,426.000000,NaN,5301.000000,NaN,NaN,NaN,2017.000000,2017.000000,NaN,32.000000,NaN,NaN,NaN
75%,NaN,NaN,643.000000,NaN,5611.000000,NaN,NaN,NaN,2020.000000,2020.000000,NaN,132.000000,NaN,NaN,NaN
max,NaN,NaN,894.000000,NaN,5611.000000,NaN,NaN,NaN,2023.000000,2023.000000,NaN,27529.000000,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_fao_dispo.head()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (FBS),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FBS,Bilans Alimentaires (2010-),4,Afghanistan,5511,Production,S2734,Viande de Volailles,2010,2010,1000 t,28.00,I,Valeur imputée par une agence réceptrice,NaN
1,FBS,Bilans Alimentaires (2010-),4,Afghanistan,5611,Importations - quantité,S2734,Viande de Volailles,2010,2010,1000 t,39.00,I,Valeur imputée par une agence réceptrice,NaN
2,FBS,Bilans Alimentaires (2010-),4,Afghanistan,5301,Disponibilité intérieure,S2734,Viande de Volailles,2010,2010,1000 t,65.00,I,Valeur imputée par une agence réceptrice,NaN
3,FBS,Bilans Alimentaires (2010-),4,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,S2734,Viande de Volailles,2010,2010,kg/personne,2.28,E,Valeur estimée,NaN
4,FBS,Bilans Alimentaires (2010-),4,Afghanistan,5511,Production,S2734,Viande de Volailles,2011,2011,1000 t,26.00,I,Valeur imputée par une agence réceptrice,NaN

In [ ]:
#Dernières lignes
df_fao_dispo.tail()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (FBS),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
9657,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,S2734,Viande de Volailles,2022,2022,kg/personne,7.69,E,Valeur estimée,NaN
9658,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,5511,Production,S2734,Viande de Volailles,2023,2023,1000 t,98.00,I,Valeur imputée par une agence réceptrice,NaN
9659,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,5611,Importations - quantité,S2734,Viande de Volailles,2023,2023,1000 t,8.00,I,Valeur imputée par une agence réceptrice,NaN
9660,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,5301,Disponibilité intérieure,S2734,Viande de Volailles,2023,2023,1000 t,106.00,I,Valeur imputée par une agence réceptrice,NaN
9661,FBS,Bilans Alimentaires (2010-),716,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,S2734,Viande de Volailles,2023,2023,kg/personne,6.46,E,Valeur estimée,NaN

Bilan :
*   Colonne "Note" vide (NaN) : à supprimer
*   Pas de PK native
*   Pas de NaN sur les autres colonnes
*   179 pays différents

### 2.1.2 - Nettoyage

In [ ]:
#Suppression des colonnes superflues
df_fao_dispo_c = df_fao_dispo.drop(columns=['Code Domaine','Domaine','Code Élément','Code Produit (FBS)','Produit','Code année','Symbole','Description du Symbole','Note'])
df_fao_dispo_c['Élément'] = df_fao_dispo_c['Élément'] + ' (' + df_fao_dispo_c['Unité'] + ')'
df_fao_dispo_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9662 entries, 0 to 9661
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code zone (M49)  9662 non-null   int64
 1   Zone             9662 non-null   object
 2   Élément          9662 non-null   object
 3   Année            9662 non-null   int64
 4   Unité            9662 non-null   object
 5   Valeur           9662 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 453.0+ KB

### 2.1.3 - Mise en forme

In [ ]:
#Mise en forme pivot
df_fao_dispo_p = df_fao_dispo_c.pivot_table(index=['Zone','Code zone (M49)','Année'], columns='Élément', values='Valeur', aggfunc='sum').reset_index()
df_fao_dispo_p

Élément,Zone,Code zone (M49),Année,Disponibilité alimentaire en quantité (kg/personne/an) (kg/personne),Disponibilité intérieure (1000 t),Importations - quantité (1000 t),Production (1000 t)
0,Afghanistan,4,2010,2.28,65.0,39.0,28.0
1,Afghanistan,4,2011,1.91,56.0,51.0,26.0
2,Afghanistan,4,2012,2.04,62.0,22.0,25.0
3,Afghanistan,4,2013,2.10,67.0,48.0,26.0
4,Afghanistan,4,2014,2.10,69.0,43.0,25.0
...,...,...,...,...,...,...,...
2420,Îles Salomon,90,2019,6.31,5.0,4.0,0.0
2421,Îles Salomon,90,2020,7.29,5.0,5.0,0.0
2422,Îles Salomon,90,2021,8.46,6.0,6.0,0.0
2423,Îles Salomon,90,2022,8.72,7.0,7.0,0.0
2424,Îles Salomon,90,2023,9.30,7.0,7.0,0.0

In [ ]:
#Mise en forme finale
df_fao_dispo_f = df_fao_dispo_p.rename(columns={'Zone':'Pays','Code zone (M49)':'Code pays','Disponibilité alimentaire en quantité (kg/personne/an) (kg/personne)':'Dispo viande volaille (kg/personne/an)','Disponibilité intérieure (1000 t)':'Dispo intérieure viande volaille (1000 t)','Importations - quantité (1000 t)':'Import viande volaille (1000 t)','Production (1000 t)':'Production viande volaille (1000 t)'})
colonne_a_deplacer = df_fao_dispo_f.pop('Dispo intérieure viande volaille (1000 t)')
df_fao_dispo_f.insert(6, 'Dispo intérieure viande volaille (1000 t)', colonne_a_deplacer)
df_fao_dispo_f.columns.name = None
df_fao_dispo_f = df_fao_dispo_f.dropna()
df_fao_dispo_f

,Pays,Code pays,Année,Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),Production viande volaille (1000 t),Dispo intérieure viande volaille (1000 t)
0,Afghanistan,4,2010,2.28,39.0,28.0,65.0
1,Afghanistan,4,2011,1.91,51.0,26.0,56.0
2,Afghanistan,4,2012,2.04,22.0,25.0,62.0
3,Afghanistan,4,2013,2.10,48.0,26.0,67.0
4,Afghanistan,4,2014,2.10,43.0,25.0,69.0
...,...,...,...,...,...,...,...
2420,Îles Salomon,90,2019,6.31,4.0,0.0,5.0
2421,Îles Salomon,90,2020,7.29,5.0,0.0,5.0
2422,Îles Salomon,90,2021,8.46,6.0,0.0,6.0
2423,Îles Salomon,90,2022,8.72,7.0,0.0,7.0
2424,Îles Salomon,90,2023,9.30,7.0,0.0,7.0

In [ ]:
#Caractéristiques
df_fao_dispo_f.info()
print("\n")
df_fao_dispo_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 2387 entries, 0 to 2424
Data columns (total 7 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Pays                                       2387 non-null   object
 1   Code pays                                  2387 non-null   int64
 2   Année                                      2387 non-null   int64
 3   Dispo viande volaille (kg/personne/an)     2387 non-null   float64
 4   Import viande volaille (1000 t)            2387 non-null   float64
 5   Production viande volaille (1000 t)        2387 non-null   float64
 6   Dispo intérieure viande volaille (1000 t)  2387 non-null   float64
dtypes: float64(4), int64(2), object(1)
memory usage: 149.2+ KB

,Pays,Code pays,Année,Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),Production viande volaille (1000 t),Dispo intérieure viande volaille (1000 t)
count,2387,2387.000000,2387.000000,2387.000000,2387.000000,2387.000000,2387.000000
unique,176,NaN,NaN,NaN,NaN,NaN,NaN
top,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN
freq,14,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,431.713867,2016.556347,22.274114,94.422287,824.444072,800.260578
std,NaN,252.986997,4.037605,17.538816,223.247603,2952.370816,2716.104439
min,NaN,4.000000,2010.000000,0.400000,0.000000,0.000000,0.000000
25%,NaN,214.000000,2013.000000,7.720000,3.000000,12.000000,30.500000
50%,NaN,426.000000,2017.000000,19.220000,18.000000,76.000000,110.000000
75%,NaN,646.000000,2020.000000,31.505000,80.500000,390.000000,379.500000
max,NaN,894.000000,2023.000000,121.050000,2396.000000,26407.000000,27529.000000

## 2.2 - Analyse exploratoire df_fao_healthydiet

### 2.2.1 - Evaluation du dataset

In [ ]:
#Caractéristiques
df_fao_healthydiet.info()
print("\n")
df_fao_healthydiet.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            1400 non-null   object
 1   Domaine                 1400 non-null   object
 2   Code zone (M49)         1400 non-null   int64
 3   Zone                    1400 non-null   object
 4   Code Élément            1400 non-null   int64
 5   Élément                 1400 non-null   object
 6   Code Produit            1400 non-null   int64
 7   Produit                 1400 non-null   object
 8   Code année              1400 non-null   int64
 9   Année                   1400 non-null   int64
 10  Édition                 1400 non-null   object
 11  Unité                   1400 non-null   object
 12  Valeur                  1209 non-null   object
 13  Symbole                 1400 non-null   object
 14  Description du Symbole  1400 non-null   object
dtypes: int64(5), object(10)
memory usage: 164.2+ KB

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Édition,Unité,Valeur,Symbole,Description du Symbole
count,1400,1400,1400.000000,1400,1400.0,1400,1400.0,1400,1400.000000,1400.000000,1400,1400,1209,1400,1400
unique,1,1,NaN,175,NaN,1,NaN,1,NaN,NaN,1,1,331,3,3
top,CAHD,Coût et abordabilité d’une alimentation saine\...,NaN,Afrique du Sud,NaN,Valeur,NaN,Number of people unable to afford a healthy di...,NaN,NaN,Juillet 2025 (rapport SOFI),millions de No,0.1,E,Valeur estimée
freq,1400,1400,NaN,8,NaN,1400,NaN,1400,NaN,NaN,1400,1400,93,1209,1209
mean,NaN,NaN,419.497143,NaN,6132.0,NaN,7006.0,NaN,2020.500000,2020.500000,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,249.400617,NaN,0.0,NaN,0.0,NaN,2.292107,2.292107,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,8.000000,NaN,6132.0,NaN,7006.0,NaN,2017.000000,2017.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,196.000000,NaN,6132.0,NaN,7006.0,NaN,2018.750000,2018.750000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,417.000000,NaN,6132.0,NaN,7006.0,NaN,2020.500000,2020.500000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,643.000000,NaN,6132.0,NaN,7006.0,NaN,2022.250000,2022.250000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,894.000000,NaN,6132.0,NaN,7006.0,NaN,2024.000000,2024.000000,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_fao_healthydiet.head()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Édition,Unité,Valeur,Symbole,Description du Symbole
0,CAHD,Coût et abordabilité d’une alimentation saine\...,710,Afrique du Sud,6132,Valeur,7006,Number of people unable to afford a healthy di...,2017,2017,Juillet 2025 (rapport SOFI),millions de No,35,E,Valeur estimée
1,CAHD,Coût et abordabilité d’une alimentation saine\...,710,Afrique du Sud,6132,Valeur,7006,Number of people unable to afford a healthy di...,2018,2018,Juillet 2025 (rapport SOFI),millions de No,35.3,E,Valeur estimée
2,CAHD,Coût et abordabilité d’une alimentation saine\...,710,Afrique du Sud,6132,Valeur,7006,Number of people unable to afford a healthy di...,2019,2019,Juillet 2025 (rapport SOFI),millions de No,35.9,E,Valeur estimée
3,CAHD,Coût et abordabilité d’une alimentation saine\...,710,Afrique du Sud,6132,Valeur,7006,Number of people unable to afford a healthy di...,2020,2020,Juillet 2025 (rapport SOFI),millions de No,37.4,E,Valeur estimée
4,CAHD,Coût et abordabilité d’une alimentation saine\...,710,Afrique du Sud,6132,Valeur,7006,Number of people unable to afford a healthy di...,2021,2021,Juillet 2025 (rapport SOFI),millions de No,37.6,E,Valeur estimée

In [ ]:
#Dernières lignes
df_fao_healthydiet.tail()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Édition,Unité,Valeur,Symbole,Description du Symbole
1395,CAHD,Coût et abordabilité d’une alimentation saine\...,716,Zimbabwe,6132,Valeur,7006,Number of people unable to afford a healthy di...,2020,2020,Juillet 2025 (rapport SOFI),millions de No,NaN,Q,Valeur manquante; supprimée
1396,CAHD,Coût et abordabilité d’une alimentation saine\...,716,Zimbabwe,6132,Valeur,7006,Number of people unable to afford a healthy di...,2021,2021,Juillet 2025 (rapport SOFI),millions de No,NaN,Q,Valeur manquante; supprimée
1397,CAHD,Coût et abordabilité d’une alimentation saine\...,716,Zimbabwe,6132,Valeur,7006,Number of people unable to afford a healthy di...,2022,2022,Juillet 2025 (rapport SOFI),millions de No,NaN,Q,Valeur manquante; supprimée
1398,CAHD,Coût et abordabilité d’une alimentation saine\...,716,Zimbabwe,6132,Valeur,7006,Number of people unable to afford a healthy di...,2023,2023,Juillet 2025 (rapport SOFI),millions de No,NaN,Q,Valeur manquante; supprimée
1399,CAHD,Coût et abordabilité d’une alimentation saine\...,716,Zimbabwe,6132,Valeur,7006,Number of people unable to afford a healthy di...,2024,2024,Juillet 2025 (rapport SOFI),millions de No,NaN,Q,Valeur manquante; supprimée

Bilan :
*   191 valeurs manquantes dans colonne "Valeur" (NaN)
*   Pas de Pk native
*   Pas de NaN sur les autres colonnes
*   175 pays différents

### 2.2.2 - Nettoyage

In [ ]:
#Suppression des colonnes superflues et conversion des NaN en null
df_fao_healthydiet_c = df_fao_healthydiet.drop(columns=['Code Domaine','Domaine','Code Élément','Élément','Code Produit','Code année','Édition','Unité','Symbole','Description du Symbole'])
df_fao_healthydiet_c['Valeur'] = pd.to_numeric(df_fao_healthydiet_c['Valeur'], errors='coerce')
df_fao_healthydiet_c = df_fao_healthydiet_c.fillna(0)
df_fao_healthydiet_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code zone (M49)  1400 non-null   int64
 1   Zone             1400 non-null   object
 2   Produit          1400 non-null   object
 3   Année            1400 non-null   int64
 4   Valeur           1400 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 54.8+ KB

### 2.2.3 - Mise en forme

In [ ]:
#Mise en forme pivot
df_fao_healthydiet_p = df_fao_healthydiet_c.pivot_table(index=['Zone','Code zone (M49)','Année'], columns='Produit', values='Valeur', aggfunc='sum').reset_index()
df_fao_healthydiet_p

Produit,Zone,Code zone (M49),Année,"Number of people unable to afford a healthy diet (NUA), million"
0,Afrique du Sud,710,2017,35.0
1,Afrique du Sud,710,2018,35.3
2,Afrique du Sud,710,2019,35.9
3,Afrique du Sud,710,2020,37.4
4,Afrique du Sud,710,2021,37.6
...,...,...,...,...
1395,Îles Vierges britanniques,92,2020,0.0
1396,Îles Vierges britanniques,92,2021,0.0
1397,Îles Vierges britanniques,92,2022,0.0
1398,Îles Vierges britanniques,92,2023,0.0
1399,Îles Vierges britanniques,92,2024,0.0

In [ ]:
#Mise en forme finale
df_fao_healthydiet_f = df_fao_healthydiet_p.rename(columns={'Zone':'Pays','Code zone (M49)':'Code pays','Number of people unable to afford a healthy diet (NUA), million':'Pop sans moyen de se nourrir sainement (en million)'})
df_fao_healthydiet_f.columns.name = None
df_fao_dispo_f = df_fao_dispo_f.dropna()
df_fao_healthydiet_f

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million)
0,Afrique du Sud,710,2017,35.0
1,Afrique du Sud,710,2018,35.3
2,Afrique du Sud,710,2019,35.9
3,Afrique du Sud,710,2020,37.4
4,Afrique du Sud,710,2021,37.6
...,...,...,...,...
1395,Îles Vierges britanniques,92,2020,0.0
1396,Îles Vierges britanniques,92,2021,0.0
1397,Îles Vierges britanniques,92,2022,0.0
1398,Îles Vierges britanniques,92,2023,0.0
1399,Îles Vierges britanniques,92,2024,0.0

In [ ]:
#Caractéristiques
df_fao_healthydiet_f.info()
print("\n")
df_fao_healthydiet_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 4 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Pays                                                 1400 non-null   object
 1   Code pays                                            1400 non-null   int64
 2   Année                                                1400 non-null   int64
 3   Pop sans moyen de se nourrir sainement (en million)  1400 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 43.9+ KB

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million)
count,1400,1400.000000,1400.000000,1400.000000
unique,175,NaN,NaN,NaN
top,Afrique du Sud,NaN,NaN,NaN
freq,8,NaN,NaN,NaN
mean,NaN,419.497143,2020.500000,15.158643
std,NaN,249.400617,2.292107,61.546270
min,NaN,8.000000,2017.000000,0.000000
25%,NaN,196.000000,2018.750000,0.100000
50%,NaN,417.000000,2020.500000,1.300000
75%,NaN,643.000000,2022.250000,9.100000
max,NaN,894.000000,2024.000000,804.900000

## 2.3 - Analyse exploratoire df_fao_PIB

### 2.3.1 - Evaluation du dataset

In [ ]:
#Caractéristiques
df_fao_PIB.info()
print("\n")
df_fao_PIB.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2837 entries, 0 to 2836
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            2837 non-null   object
 1   Domaine                 2837 non-null   object
 2   Code zone (M49)         2837 non-null   int64
 3   Zone                    2837 non-null   object
 4   Code Élément            2837 non-null   int64
 5   Élément                 2837 non-null   object
 6   Code Produit            2837 non-null   int64
 7   Produit                 2837 non-null   object
 8   Code année              2837 non-null   int64
 9   Année                   2837 non-null   int64
 10  Unité                   2837 non-null   object
 11  Valeur                  2837 non-null   int64
 12  Symbole                 2837 non-null   object
 13  Description du Symbole  2837 non-null   object
 14  Note                    0 non-null      float64
dtypes: float64(1), int64(6), object(8)
memory usage: 332.6+ KB

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
count,2837,2837,2837.000000,2837,2837.0,2837,2837.0,2837,2837.000000,2837.000000,2837,2837.000000,2837,2837,0.0
unique,1,1,NaN,190,NaN,1,NaN,1,NaN,NaN,1,NaN,1,1,NaN
top,FS,Données de la sécurité alimentaire,NaN,Afrique du Sud,NaN,Valeur,NaN,"PIB par habitant, ($ PPA internationaux consta...",NaN,NaN,Int$/cap,NaN,X,Chiffre de source externe,NaN
freq,2837,2837,NaN,15,NaN,2837,NaN,2837,NaN,NaN,2837,NaN,2837,2837,NaN
mean,NaN,NaN,425.136764,NaN,6126.0,NaN,22013.0,NaN,2016.981671,2016.981671,NaN,24660.194572,NaN,NaN,NaN
std,NaN,NaN,251.414818,NaN,0.0,NaN,0.0,NaN,4.306613,4.306613,NaN,26016.369990,NaN,NaN,NaN
min,NaN,NaN,4.000000,NaN,6126.0,NaN,22013.0,NaN,2010.000000,2010.000000,NaN,829.000000,NaN,NaN,NaN
25%,NaN,NaN,208.000000,NaN,6126.0,NaN,22013.0,NaN,2013.000000,2013.000000,NaN,5531.000000,NaN,NaN,NaN
50%,NaN,NaN,426.000000,NaN,6126.0,NaN,22013.0,NaN,2017.000000,2017.000000,NaN,15070.000000,NaN,NaN,NaN
75%,NaN,NaN,642.000000,NaN,6126.0,NaN,22013.0,NaN,2021.000000,2021.000000,NaN,36127.000000,NaN,NaN,NaN
max,NaN,NaN,894.000000,NaN,6126.0,NaN,22013.0,NaN,2024.000000,2024.000000,NaN,174339.000000,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_fao_PIB.head()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,4,Afghanistan,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2010,2010,Int$/cap,2849,X,Chiffre de source externe,NaN
1,FS,Données de la sécurité alimentaire,4,Afghanistan,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2011,2011,Int$/cap,2757,X,Chiffre de source externe,NaN
2,FS,Données de la sécurité alimentaire,4,Afghanistan,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2012,2012,Int$/cap,2985,X,Chiffre de source externe,NaN
3,FS,Données de la sécurité alimentaire,4,Afghanistan,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2013,2013,Int$/cap,3047,X,Chiffre de source externe,NaN
4,FS,Données de la sécurité alimentaire,4,Afghanistan,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2014,2014,Int$/cap,3018,X,Chiffre de source externe,NaN

In [ ]:
#Dernières lignes
df_fao_PIB.tail()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
2832,FS,Données de la sécurité alimentaire,716,Zimbabwe,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2020,2020,Int$/cap,2987,X,Chiffre de source externe,NaN
2833,FS,Données de la sécurité alimentaire,716,Zimbabwe,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2021,2021,Int$/cap,3185,X,Chiffre de source externe,NaN
2834,FS,Données de la sécurité alimentaire,716,Zimbabwe,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2022,2022,Int$/cap,3323,X,Chiffre de source externe,NaN
2835,FS,Données de la sécurité alimentaire,716,Zimbabwe,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2023,2023,Int$/cap,3442,X,Chiffre de source externe,NaN
2836,FS,Données de la sécurité alimentaire,716,Zimbabwe,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2024,2024,Int$/cap,3450,X,Chiffre de source externe,NaN

Bilan :
*   Colonne "Note" vide (NaN) : à supprimer
*   Pas de pk native
*   Pas d'autre colonne avec NaN
*   190 pays différents

### 2.3.2 - Nettoyage

In [ ]:
#Suppression des colonnes superflues
df_fao_PIB_c = df_fao_PIB.drop(columns=['Code Domaine','Domaine','Code Élément','Élément','Code Produit','Code année','Symbole','Unité','Symbole','Description du Symbole','Note'])
df_fao_PIB_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2837 entries, 0 to 2836
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code zone (M49)  2837 non-null   int64
 1   Zone             2837 non-null   object
 2   Produit          2837 non-null   object
 3   Année            2837 non-null   int64
 4   Valeur           2837 non-null   int64
dtypes: int64(3), object(2)
memory usage: 110.9+ KB

### 2.3.3 - Mise en forme

In [ ]:
#Mise en forme pivot
df_fao_PIB_p = df_fao_PIB_c.pivot_table(index=['Zone','Code zone (M49)','Année'], columns='Produit', values='Valeur', aggfunc='sum').reset_index()
df_fao_PIB_p

Produit,Zone,Code zone (M49),Année,"PIB par habitant, ($ PPA internationaux constants de 2021)"
0,Afghanistan,4,2010,2849
1,Afghanistan,4,2011,2757
2,Afghanistan,4,2012,2985
3,Afghanistan,4,2013,3047
4,Afghanistan,4,2014,3018
...,...,...,...,...
2832,Îles Salomon,90,2020,2515
2833,Îles Salomon,90,2021,2518
2834,Îles Salomon,90,2022,2518
2835,Îles Salomon,90,2023,2524
2836,Îles Salomon,90,2024,2527

In [ ]:
#Mise en forme finale
df_fao_PIB_f = df_fao_PIB_p.rename(columns={'Zone':'Pays','Code zone (M49)':'Code pays','PIB par habitant, ($ PPA internationaux constants de 2021)':'PIB/hab ($ PPA internationaux constants de 2021)'})
df_fao_PIB_f.columns.name = None
df_fao_PIB_f = df_fao_PIB_f.dropna()
df_fao_PIB_f

,Pays,Code pays,Année,PIB/hab ($ PPA internationaux constants de 2021)
0,Afghanistan,4,2010,2849
1,Afghanistan,4,2011,2757
2,Afghanistan,4,2012,2985
3,Afghanistan,4,2013,3047
4,Afghanistan,4,2014,3018
...,...,...,...,...
2832,Îles Salomon,90,2020,2515
2833,Îles Salomon,90,2021,2518
2834,Îles Salomon,90,2022,2518
2835,Îles Salomon,90,2023,2524
2836,Îles Salomon,90,2024,2527

In [ ]:
#Caractéristiques
df_fao_PIB_f.info()
print("\n")
df_fao_PIB_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2837 entries, 0 to 2836
Data columns (total 4 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Pays                                              2837 non-null   object
 1   Code pays                                         2837 non-null   int64
 2   Année                                             2837 non-null   int64
 3   PIB/hab ($ PPA internationaux constants de 2021)  2837 non-null   int64
dtypes: int64(3), object(1)
memory usage: 88.8+ KB

,Pays,Code pays,Année,PIB/hab ($ PPA internationaux constants de 2021)
count,2837,2837.000000,2837.000000,2837.000000
unique,190,NaN,NaN,NaN
top,Afrique du Sud,NaN,NaN,NaN
freq,15,NaN,NaN,NaN
mean,NaN,425.136764,2016.981671,24660.194572
std,NaN,251.414818,4.306613,26016.369990
min,NaN,4.000000,2010.000000,829.000000
25%,NaN,208.000000,2013.000000,5531.000000
50%,NaN,426.000000,2017.000000,15070.000000
75%,NaN,642.000000,2021.000000,36127.000000
max,NaN,894.000000,2024.000000,174339.000000

## 2.4 - Analyse exploratoire df_fao_population

### 2.4.1 - Evaluation du dataset

In [ ]:
#Caractéristiques
df_fao_population.info()
print("\n")
df_fao_population.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9814 entries, 0 to 9813
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            9814 non-null   object
 1   Domaine                 9814 non-null   object
 2   Code zone (M49)         9814 non-null   int64
 3   Zone                    9814 non-null   object
 4   Code Élément            9814 non-null   int64
 5   Élément                 9814 non-null   object
 6   Code Produit            9814 non-null   int64
 7   Produit                 9814 non-null   object
 8   Code année              9814 non-null   int64
 9   Année                   9814 non-null   int64
 10  Unité                   9814 non-null   object
 11  Valeur                  9814 non-null   float64
 12  Symbole                 9814 non-null   object
 13  Description du Symbole  9814 non-null   object
 14  Note                    0 non-null      float64
dtypes: float64(2), int64(5), object(8)
memory usage: 1.1+ MB

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
count,9814,9814,9814.000000,9814,9814.000000,9814,9814.0,9814,9814.000000,9814.000000,9814,9.814000e+03,9814,9814,0.0
unique,1,1,NaN,238,NaN,3,NaN,1,NaN,NaN,1,NaN,2,2,NaN
top,OA,Séries temporelles annuelles,NaN,Afghanistan,NaN,Population rurale,NaN,Population-Estimations,NaN,NaN,1000 No,NaN,X,Chiffre de source externe,NaN
freq,9814,9814,NaN,42,NaN,3272,NaN,9814,NaN,NaN,9814,NaN,9811,9811,NaN
mean,NaN,NaN,435.598838,NaN,541.006114,NaN,3010.0,NaN,2016.508967,2016.508967,NaN,2.560766e+04,NaN,NaN,NaN
std,NaN,NaN,251.613117,NaN,21.601525,NaN,0.0,NaN,4.027176,4.027176,NaN,1.150844e+05,NaN,NaN,NaN
min,NaN,NaN,4.000000,NaN,511.000000,NaN,3010.0,NaN,2010.000000,2010.000000,NaN,0.000000e+00,NaN,NaN,NaN
25%,NaN,NaN,218.000000,NaN,511.000000,NaN,3010.0,NaN,2013.000000,2013.000000,NaN,2.141300e+02,NaN,NaN,NaN
50%,NaN,NaN,438.000000,NaN,551.000000,NaN,3010.0,NaN,2017.000000,2017.000000,NaN,2.918486e+03,NaN,NaN,NaN
75%,NaN,NaN,654.000000,NaN,561.000000,NaN,3010.0,NaN,2020.000000,2020.000000,NaN,1.176443e+04,NaN,NaN,NaN
max,NaN,NaN,894.000000,NaN,561.000000,NaN,3010.0,NaN,2023.000000,2023.000000,NaN,1.458175e+06,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_fao_population.head()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,4,Afghanistan,511,Population totale,3010,Population-Estimations,2010,2010,1000 No,28284.089,X,Chiffre de source externe,NaN
1,OA,Séries temporelles annuelles,4,Afghanistan,551,Population rurale,3010,Population-Estimations,2010,2010,1000 No,21966.187,X,Chiffre de source externe,NaN
2,OA,Séries temporelles annuelles,4,Afghanistan,561,Population urbaine,3010,Population-Estimations,2010,2010,1000 No,6836.980,X,Chiffre de source externe,NaN
3,OA,Séries temporelles annuelles,4,Afghanistan,511,Population totale,3010,Population-Estimations,2011,2011,1000 No,29347.708,X,Chiffre de source externe,NaN
4,OA,Séries temporelles annuelles,4,Afghanistan,551,Population rurale,3010,Population-Estimations,2011,2011,1000 No,22594.126,X,Chiffre de source externe,NaN

In [ ]:
#Dernières lignes
df_fao_population.tail()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
9809,OA,Séries temporelles annuelles,716,Zimbabwe,551,Population rurale,3010,Population-Estimations,2022,2022,1000 No,12464.597,X,Chiffre de source externe,NaN
9810,OA,Séries temporelles annuelles,716,Zimbabwe,561,Population urbaine,3010,Population-Estimations,2022,2022,1000 No,5972.826,X,Chiffre de source externe,NaN
9811,OA,Séries temporelles annuelles,716,Zimbabwe,511,Population totale,3010,Population-Estimations,2023,2023,1000 No,16340.822,X,Chiffre de source externe,NaN
9812,OA,Séries temporelles annuelles,716,Zimbabwe,551,Population rurale,3010,Population-Estimations,2023,2023,1000 No,12695.580,X,Chiffre de source externe,NaN
9813,OA,Séries temporelles annuelles,716,Zimbabwe,561,Population urbaine,3010,Population-Estimations,2023,2023,1000 No,6117.511,X,Chiffre de source externe,NaN

Bilan :
*   Colonne "Note" vide (NaN) : à supprimer
*   Pas de pk native
*   Pas d'autre colonne avec des NaN
*   238 pays différents

### 2.4.2 - Nettoyage

In [ ]:
#Suppression des colonnes superflues
df_fao_population_c = df_fao_population.drop(columns=['Code Domaine','Domaine','Code Élément','Code Produit','Produit','Code année','Unité','Symbole','Description du Symbole','Note'])
df_fao_population_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9814 entries, 0 to 9813
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code zone (M49)  9814 non-null   int64
 1   Zone             9814 non-null   object
 2   Élément          9814 non-null   object
 3   Année            9814 non-null   int64
 4   Valeur           9814 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 383.5+ KB

### 2.4.3 - Mise en forme

In [ ]:
#Mise en forme pivot
df_fao_population_p = df_fao_population_c.pivot_table(index=['Zone','Code zone (M49)','Année'], columns='Élément', values='Valeur', aggfunc='sum').reset_index()
df_fao_population_p

Élément,Zone,Code zone (M49),Année,Population rurale,Population totale,Population urbaine
0,Afghanistan,4,2010,21966.187,28284.089,6836.980
1,Afghanistan,4,2011,22594.126,29347.708,7114.473
2,Afghanistan,4,2012,23280.663,30560.034,7416.295
3,Afghanistan,4,2013,23997.856,31622.704,7733.832
4,Afghanistan,4,2014,24703.798,32792.523,8054.222
...,...,...,...,...,...,...
3293,Îles Wallis-et-Futuna,876,2019,11.617,11.686,0.000
3294,Îles Wallis-et-Futuna,876,2020,11.551,11.616,0.000
3295,Îles Wallis-et-Futuna,876,2021,11.494,11.568,0.000
3296,Îles Wallis-et-Futuna,876,2022,11.457,11.478,0.000
3297,Îles Wallis-et-Futuna,876,2023,11.415,11.370,0.000

In [ ]:
#Mise en forme finale
df_fao_population_f = df_fao_population_p.rename(columns={'Zone':'Pays','Code zone (M49)':'Code pays','Population rurale':'Pop rurale (pour 1000)','Population totale':'Pop totale (pour 1000)','Population urbaine':'Pop urbaine (pour 1000)'})
colonne_a_deplacer = df_fao_population_f.pop('Pop totale (pour 1000)')
df_fao_population_f.insert(5, 'Pop totale (pour 1000)', colonne_a_deplacer)
df_fao_population_f.columns.name = None
df_fao_population_f = df_fao_population_f.dropna()
df_fao_population_f

,Pays,Code pays,Année,Pop rurale (pour 1000),Pop urbaine (pour 1000),Pop totale (pour 1000)
0,Afghanistan,4,2010,21966.187,6836.980,28284.089
1,Afghanistan,4,2011,22594.126,7114.473,29347.708
2,Afghanistan,4,2012,23280.663,7416.295,30560.034
3,Afghanistan,4,2013,23997.856,7733.832,31622.704
4,Afghanistan,4,2014,24703.798,8054.222,32792.523
...,...,...,...,...,...,...
3293,Îles Wallis-et-Futuna,876,2019,11.617,0.000,11.686
3294,Îles Wallis-et-Futuna,876,2020,11.551,0.000,11.616
3295,Îles Wallis-et-Futuna,876,2021,11.494,0.000,11.568
3296,Îles Wallis-et-Futuna,876,2022,11.457,0.000,11.478
3297,Îles Wallis-et-Futuna,876,2023,11.415,0.000,11.370

In [ ]:
#Caractéristiques
df_fao_population_f.info()
print("\n")
df_fao_population_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 3244 entries, 0 to 3297
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Pays                     3244 non-null   object
 1   Code pays                3244 non-null   int64
 2   Année                    3244 non-null   int64
 3   Pop rurale (pour 1000)   3244 non-null   float64
 4   Pop urbaine (pour 1000)  3244 non-null   float64
 5   Pop totale (pour 1000)   3244 non-null   float64
dtypes: float64(3), int64(2), object(1)
memory usage: 177.4+ KB

,Pays,Code pays,Année,Pop rurale (pour 1000),Pop urbaine (pour 1000),Pop totale (pour 1000)
count,3244,3244.000000,3244.000000,3244.000000,3244.000000,3.244000e+03
unique,234,NaN,NaN,NaN,NaN,NaN
top,Afghanistan,NaN,NaN,NaN,NaN,NaN
freq,14,NaN,NaN,NaN,NaN,NaN
mean,NaN,434.157830,2016.507707,17286.765677,21284.733308,3.889789e+04
std,NaN,251.487165,4.028223,81436.795670,84835.956158,1.611398e+05
min,NaN,4.000000,2010.000000,0.000000,0.000000,1.585000e+00
25%,NaN,214.000000,2013.000000,96.047000,313.533750,4.553447e+02
50%,NaN,434.000000,2017.000000,1635.663500,3081.828000,5.523550e+03
75%,NaN,646.000000,2020.000000,9422.752500,10406.699500,2.228700e+04
max,NaN,894.000000,2023.000000,906919.359000,953931.777000,1.458175e+06

## 2.5 - Analyse exploratoire df_fao_stability

### 2.5.1 - Evaluation du dataset

In [ ]:
#Caractéristiques
df_fao_stability.info()
print("\n")
df_fao_stability.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            2535 non-null   object
 1   Domaine                 2535 non-null   object
 2   Code zone (M49)         2535 non-null   int64
 3   Zone                    2535 non-null   object
 4   Code Élément            2535 non-null   int64
 5   Élément                 2535 non-null   object
 6   Code Produit            2535 non-null   int64
 7   Produit                 2535 non-null   object
 8   Code année              2535 non-null   int64
 9   Année                   2535 non-null   int64
 10  Unité                   0 non-null      float64
 11  Valeur                  2535 non-null   float64
 12  Symbole                 2535 non-null   object
 13  Description du Symbole  2535 non-null   object
 14  Note                    0 non-null      float64
dtypes: float64(3), int64(5), object(7)
memory usage: 297.2+ KB

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
count,2535,2535,2535.000000,2535,2535.0,2535,2535.0,2535,2535.000000,2535.000000,0.0,2535.000000,2535,2535,0.0
unique,1,1,NaN,196,NaN,1,NaN,1,NaN,NaN,NaN,NaN,1,1,NaN
top,FS,Données de la sécurité alimentaire,NaN,Afghanistan,NaN,Valeur,NaN,Stabilité politique et absence de violence/ter...,NaN,NaN,NaN,NaN,X,Chiffre de source externe,NaN
freq,2535,2535,NaN,13,NaN,2535,NaN,2535,NaN,NaN,NaN,NaN,2535,2535,NaN
mean,NaN,NaN,428.475740,NaN,6125.0,NaN,21032.0,NaN,2016.004734,2016.004734,NaN,-0.068998,NaN,NaN,NaN
std,NaN,NaN,254.651457,NaN,0.0,NaN,0.0,NaN,3.741865,3.741865,NaN,0.993756,NaN,NaN,NaN
min,NaN,NaN,4.000000,NaN,6125.0,NaN,21032.0,NaN,2010.000000,2010.000000,NaN,-3.130000,NaN,NaN,NaN
25%,NaN,NaN,208.000000,NaN,6125.0,NaN,21032.0,NaN,2013.000000,2013.000000,NaN,-0.680000,NaN,NaN,NaN
50%,NaN,NaN,426.000000,NaN,6125.0,NaN,21032.0,NaN,2016.000000,2016.000000,NaN,0.020000,NaN,NaN,NaN
75%,NaN,NaN,646.000000,NaN,6125.0,NaN,21032.0,NaN,2019.000000,2019.000000,NaN,0.780000,NaN,NaN,NaN
max,NaN,NaN,894.000000,NaN,6125.0,NaN,21032.0,NaN,2022.000000,2022.000000,NaN,1.960000,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_fao_stability.head()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2010,2010,NaN,-2.58,X,Chiffre de source externe,NaN
1,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2011,2011,NaN,-2.50,X,Chiffre de source externe,NaN
2,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2012,2012,NaN,-2.42,X,Chiffre de source externe,NaN
3,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2013,2013,NaN,-2.52,X,Chiffre de source externe,NaN
4,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2014,2014,NaN,-2.41,X,Chiffre de source externe,NaN

In [ ]:
#Dernières lignes
df_fao_stability.tail()

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
2530,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2018,2018,NaN,-0.72,X,Chiffre de source externe,NaN
2531,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2019,2019,NaN,-0.94,X,Chiffre de source externe,NaN
2532,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2020,2020,NaN,-1.05,X,Chiffre de source externe,NaN
2533,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2021,2021,NaN,-0.95,X,Chiffre de source externe,NaN
2534,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2022,2022,NaN,-0.89,X,Chiffre de source externe,NaN

Bilan :
*   Colonnes "Note" et "Unité" vides (NaN) : à supprimer
*   Pas de pk native
*   Pas d'autre colonne avec des NaN
*   196 pays différents

### 2.5.2 - Nettoyage

In [ ]:
#Suppression des colonnes superflues
df_fao_stability_c = df_fao_stability.drop(columns=['Code Domaine','Domaine','Code Élément','Élément','Code Produit','Code année','Unité','Symbole','Description du Symbole','Note'])
df_fao_stability_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code zone (M49)  2535 non-null   int64
 1   Zone             2535 non-null   object
 2   Produit          2535 non-null   object
 3   Année            2535 non-null   int64
 4   Valeur           2535 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 99.2+ KB

### 2.5.3 - Mise en forme

In [ ]:
#Mise en forme pivot
df_fao_stability_p = df_fao_stability_c.pivot_table(index=['Zone','Code zone (M49)','Année'], columns='Produit', values='Valeur', aggfunc='sum').reset_index()
df_fao_stability_p

Produit,Zone,Code zone (M49),Année,Stabilité politique et absence de violence/terrorisme (indice)
0,Afghanistan,4,2010,-2.58
1,Afghanistan,4,2011,-2.50
2,Afghanistan,4,2012,-2.42
3,Afghanistan,4,2013,-2.52
4,Afghanistan,4,2014,-2.41
...,...,...,...,...
2530,Îles Salomon,90,2018,0.36
2531,Îles Salomon,90,2019,0.50
2532,Îles Salomon,90,2020,0.56
2533,Îles Salomon,90,2021,0.54
2534,Îles Salomon,90,2022,0.41

In [ ]:
#Mise en forme finale
df_fao_stability_f = df_fao_stability_p.rename(columns={'Zone':'Pays','Code zone (M49)':'Code pays','Stabilité politique et absence de violence/terrorisme (indice)':'Indice stabilité politique'})
df_fao_stability_f.columns.name = None
df_fao_stability_f = df_fao_stability_f.dropna()
df_fao_stability_f

              Pays  Code pays  Année  Indice stabilité politique
0      Afghanistan          4   2010                       -2.58
1      Afghanistan          4   2011                       -2.50
2      Afghanistan          4   2012                       -2.42
3      Afghanistan          4   2013                       -2.52
4      Afghanistan          4   2014                       -2.41
...            ...        ...    ...                         ...
2530  Îles Salomon         90   2018                        0.36
2531  Îles Salomon         90   2019                        0.50
2532  Îles Salomon         90   2020                        0.56
2533  Îles Salomon         90   2021                        0.54
2534  Îles Salomon         90   2022                        0.41

[2535 rows x 4 columns]

In [ ]:
#Caractéristiques
df_fao_stability_f.info()
print("\n")
df_fao_stability_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2535 entries, 0 to 2534
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pays                        2535 non-null   object
 1   Code pays                   2535 non-null   int64
 2   Année                       2535 non-null   int64
 3   Indice stabilité politique  2535 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 79.3+ KB

               Pays    Code pays        Année  Indice stabilité politique
count          2535  2535.000000  2535.000000                 2535.000000
unique          196          NaN          NaN                         NaN
top     Afghanistan          NaN          NaN                         NaN
freq             13          NaN          NaN                         NaN
mean            NaN   428.475740  2016.004734                   -0.068998
std             NaN   254.651457     3.741865                    0.993756
min             NaN     4.000000  2010.000000                   -3.130000
25%             NaN   208.000000  2013.000000                   -0.680000
50%             NaN   426.000000  2016.000000                    0.020000
75%             NaN   646.000000  2019.000000                    0.780000
max             NaN   894.000000  2022.000000                    1.960000

## 2.6 - Analyse exploratoire df_wbg_index

### 2.6.1 - Evaluation du dataset

In [ ]:
#Caractéristiques
df_wbg_index.info()
print("\n")
df_wbg_index.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1307 entries, 0 to 1306
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   1304 non-null   object
 1   Country Code   1302 non-null   object
 2   Series Name    1302 non-null   object
 3   Series Code    1302 non-null   object
 4   2010 [YR2010]  1302 non-null   object
 5   2011 [YR2011]  1302 non-null   object
 6   2012 [YR2012]  1302 non-null   object
 7   2013 [YR2013]  1302 non-null   object
 8   2014 [YR2014]  1302 non-null   object
 9   2015 [YR2015]  1302 non-null   object
 10  2016 [YR2016]  1302 non-null   object
 11  2017 [YR2017]  1302 non-null   object
 12  2018 [YR2018]  1302 non-null   object
 13  2019 [YR2019]  1302 non-null   object
 14  2020 [YR2020]  1302 non-null   object
 15  2021 [YR2021]  1302 non-null   object
 16  2022 [YR2022]  1302 non-null   object
 17  2023 [YR2023]  1302 non-null   object
 18  2024 [YR2024]  1302 non-null   object
 19  2025 [YR2025]  1302 non-null   object
dtypes: object(20)
memory usage: 204.3+ KB

,Country Name,Country Code,Series Name,Series Code,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
count,1304,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302,1302
unique,219,217,6,6,740,513,712,505,971,499,973,495,702,492,486,483,504,474,1,1
top,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..
freq,6,6,217,217,218,679,220,679,204,677,200,677,200,677,677,677,263,677,1302,1302

In [ ]:
#Premières lignes
df_wbg_index.head()

,Country Name,Country Code,Series Name,Series Code,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,42.7,43.2,69.1,68,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3,..,..
1,Afghanistan,AFG,Logistics performance index: Overall (1=low to...,LP.LPI.OVRL.XQ,2.24,..,2.3,..,2.069573,..,2.141282,..,1.95,..,..,..,1.9,..,..,..
2,Afghanistan,AFG,Logistics performance index: Frequency with wh...,LP.LPI.TIME.XQ,2.61,..,2.8,..,2.482138,..,2.611203,..,2.38,..,..,..,2.3,..,..,..
3,Afghanistan,AFG,Logistics performance index: Quality of trade ...,LP.LPI.INFR.XQ,1.87,..,2,..,1.818951,..,1.835473,..,1.81,..,..,..,1.7,..,..,..
4,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,-1.64539110660553,-1.60047078132629,-1.43037283420563,-1.44596064090729,-1.36493408679962,-1.35471308231354,-1.54022777080536,-1.53007459640503,-1.50287592411041,-1.41931009292603,-1.49336087703705,-1.15226578712463,-1.18368434906006,-1.15493178367615,..,..

In [ ]:
#Dernières lignes
df_wbg_index.tail(6)

,Country Name,Country Code,Series Name,Series Code,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
1301,Zimbabwe,ZWE,Rule of Law: Estimate,RL.EST,-1.83763182163239,-1.79394936561584,-1.63018405437469,-1.5877091884613,-1.44185197353363,-1.33903956413269,-1.391646027565,-1.39540266990662,-1.29305863380432,-1.3110408782959,-1.33736205101013,-1.28212225437164,-1.23702752590179,-1.27714252471924,..,..
1302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1305,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1306,Last Updated: 02/24/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Bilan :
*   5 dernières lignes vides (NaN) : à supprimer
*   Pas de colonne avec NaN
*   Pas d'autre ligne avec NaN
*   217 pays différents
*   Pas de pk native

### 2.6.2 - Nettoyage

In [ ]:
#Suppression des colonnes et lignes superflues
df_wbg_index_c = df_wbg_index.drop(columns=['Series Code'])
df_wbg_index_c = df_wbg_index_c .dropna(subset=['Country Code'])
df_wbg_index_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1302 entries, 0 to 1301
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   1302 non-null   object
 1   Country Code   1302 non-null   object
 2   Series Name    1302 non-null   object
 3   2010 [YR2010]  1302 non-null   object
 4   2011 [YR2011]  1302 non-null   object
 5   2012 [YR2012]  1302 non-null   object
 6   2013 [YR2013]  1302 non-null   object
 7   2014 [YR2014]  1302 non-null   object
 8   2015 [YR2015]  1302 non-null   object
 9   2016 [YR2016]  1302 non-null   object
 10  2017 [YR2017]  1302 non-null   object
 11  2018 [YR2018]  1302 non-null   object
 12  2019 [YR2019]  1302 non-null   object
 13  2020 [YR2020]  1302 non-null   object
 14  2021 [YR2021]  1302 non-null   object
 15  2022 [YR2022]  1302 non-null   object
 16  2023 [YR2023]  1302 non-null   object
 17  2024 [YR2024]  1302 non-null   object
 18  2025 [YR2025]  1302 non-null   object
dtypes: object(19)
memory usage: 203.4+ KB

### 2.6.3 - Mise en forme

In [ ]:
#Mise en forme tableau
df_wbg_index_t = df_wbg_index_c.melt(id_vars=['Country Code','Country Name','Series Name'], var_name='Année brute', value_name='Valeur')
df_wbg_index_t[['Année', 'Code Année']] = df_wbg_index_t['Année brute'].str.split(' ', expand=True)
df_wbg_index_t

,Country Code,Country Name,Series Name,Année brute,Valeur,Année,Code Année
0,AFG,Afghanistan,Access to electricity (% of population),2010 [YR2010],42.7,2010,[YR2010]
1,AFG,Afghanistan,Logistics performance index: Overall (1=low to...,2010 [YR2010],2.24,2010,[YR2010]
2,AFG,Afghanistan,Logistics performance index: Frequency with wh...,2010 [YR2010],2.61,2010,[YR2010]
3,AFG,Afghanistan,Logistics performance index: Quality of trade ...,2010 [YR2010],1.87,2010,[YR2010]
4,AFG,Afghanistan,Control of Corruption: Estimate,2010 [YR2010],-1.64539110660553,2010,[YR2010]
...,...,...,...,...,...,...,...
20827,ZWE,Zimbabwe,Logistics performance index: Overall (1=low to...,2025 [YR2025],..,2025,[YR2025]
20828,ZWE,Zimbabwe,Logistics performance index: Frequency with wh...,2025 [YR2025],..,2025,[YR2025]
20829,ZWE,Zimbabwe,Logistics performance index: Quality of trade ...,2025 [YR2025],..,2025,[YR2025]
20830,ZWE,Zimbabwe,Control of Corruption: Estimate,2025 [YR2025],..,2025,[YR2025]
20831,ZWE,Zimbabwe,Rule of Law: Estimate,2025 [YR2025],..,2025,[YR2025]

In [ ]:
#Mise en forme pivot
df_wbg_index_p = df_wbg_index_t.pivot_table(index=['Country Code','Country Name','Année'], columns='Series Name', values='Valeur', aggfunc='sum').reset_index()
df_wbg_index_p = df_wbg_index_p.drop(columns=['Logistics performance index: Frequency with which shipments reach consignee within scheduled or expected time (1=low to 5=high)','Logistics performance index: Quality of trade and transport-related infrastructure (1=low to 5=high)'])
df_wbg_index_p

Series Name,Country Code,Country Name,Année,Access to electricity (% of population),Control of Corruption: Estimate,Logistics performance index: Overall (1=low to 5=high),Rule of Law: Estimate
0,ABW,Aruba,2010,93.4,1.12129557132721,..,1.41611361503601
1,ABW,Aruba,2011,100,1.10294651985168,..,1.3224583864212
2,ABW,Aruba,2012,100,1.09523594379425,..,1.30978834629059
3,ABW,Aruba,2013,100,1.11960065364838,..,1.29263317584991
4,ABW,Aruba,2014,100,1.01400101184845,..,1.0364248752594
...,...,...,...,...,...,...,...
3467,ZWE,Zimbabwe,2021,49,-1.27714729309082,..,-1.28212225437164
3468,ZWE,Zimbabwe,2022,50.1,-1.25996947288513,2.5,-1.23702752590179
3469,ZWE,Zimbabwe,2023,62,-1.26121604442596,..,-1.27714252471924
3470,ZWE,Zimbabwe,2024,..,..,..,..
3471,ZWE,Zimbabwe,2025,..,..,..,..

In [ ]:
#Mise en forme finale
df_wbg_index_f = df_wbg_index_p.rename(columns={'Country Code':'Id pays','Country Name':'Pays','Access to electricity (% of population)':'Taux pop accès électricité','Control of Corruption: Estimate':'Indice corruption','Logistics performance index: Overall (1=low to 5=high)':'Indice perf log','Rule of Law: Estimate':'Indice état de droit'})
df_wbg_index_f.columns.name = None
df_wbg_index_f = df_wbg_index_f.replace('..', np.nan)
df_wbg_index_f = df_wbg_index_f.dropna()
df_wbg_index_f

,Id pays,Pays,Année,Taux pop accès électricité,Indice corruption,Indice perf log,Indice état de droit
16,AFG,Afghanistan,2010,42.7,-1.64539110660553,2.24,-1.87005805969238
18,AFG,Afghanistan,2012,69.1,-1.43037283420563,2.3,-1.6518931388855
20,AFG,Afghanistan,2014,89.5,-1.36493408679962,2.069573,-1.4377019405365
22,AFG,Afghanistan,2016,97.7,-1.54022777080536,2.141282,-1.52253365516663
24,AFG,Afghanistan,2018,93.4,-1.50287592411041,1.95,-1.68912386894226
...,...,...,...,...,...,...,...
3458,ZWE,Zimbabwe,2012,44,-1.38180339336395,2.55,-1.63018405437469
3460,ZWE,Zimbabwe,2014,32.3,-1.40475881099701,2.33928,-1.44185197353363
3462,ZWE,Zimbabwe,2016,42.5,-1.28866481781006,2.082408,-1.391646027565
3464,ZWE,Zimbabwe,2018,45.4,-1.24637961387634,2.12,-1.29305863380432
3468,ZWE,Zimbabwe,2022,50.1,-1.25996947288513,2.5,-1.23702752590179

In [ ]:
#Caractéristiques
df_wbg_index_f.info()
print("\n")
df_wbg_index_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 922 entries, 16 to 3468
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Id pays                     922 non-null    object
 1   Pays                        922 non-null    object
 2   Année                       922 non-null    object
 3   Taux pop accès électricité  922 non-null    object
 4   Indice corruption           922 non-null    object
 5   Indice perf log             922 non-null    object
 6   Indice état de droit        922 non-null    object
dtypes: object(7)
memory usage: 89.9+ KB

,Id pays,Pays,Année,Taux pop accès électricité,Indice corruption,Indice perf log,Indice état de droit
count,922,922,922,922,922,922,922
unique,168,168,6,320,922,507,922
top,AFG,Afghanistan,2016,100,-1.25996947288513,2.5,-1.23702752590179
freq,6,6,159,372,1,19,1

## 2.7 - Analyse exploratoire df_wbg_temperature

### 2.7.1 - Evaluation du dataset

In [ ]:
#Caractéristiques
df_wbg_temperature.info()
print("\n")
df_wbg_temperature.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   195 non-null    object
 1   Country Code   193 non-null    object
 2   Series Name    193 non-null    object
 3   Series Code    193 non-null    object
 4   2010 [YR2010]  193 non-null    object
 5   2011 [YR2011]  193 non-null    object
 6   2012 [YR2012]  193 non-null    object
 7   2013 [YR2013]  193 non-null    object
 8   2014 [YR2014]  193 non-null    object
 9   2015 [YR2015]  193 non-null    object
 10  2016 [YR2016]  193 non-null    object
 11  2017 [YR2017]  193 non-null    object
 12  2018 [YR2018]  193 non-null    object
 13  2019 [YR2019]  193 non-null    object
 14  2020 [YR2020]  193 non-null    object
 15  2021 [YR2021]  193 non-null    object
 16  2022 [YR2022]  193 non-null    object
 17  2023 [YR2023]  193 non-null    object
dtypes: object(18)
memory usage: 28.0+ KB

,Country Name,Country Code,Series Name,Series Code,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
count,195,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193,193
unique,195,193,1,1,193,192,192,192,192,192,193,192,193,192,192,193,1,1
top,Afghanistan,AFG,Land Surface Temperature,EN.LND.LTMP.DC,29.6243831,..,..,..,..,..,30.6263973,..,30.1259055,..,..,30.8741594,..,..
freq,1,1,193,193,1,2,2,2,2,2,1,2,1,2,2,1,193,193

In [ ]:
#Premières lignes
df_wbg_temperature.head()

,Country Name,Country Code,Series Name,Series Code,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Land Surface Temperature,EN.LND.LTMP.DC,29.6243831,29.1250018,27.3746873,29.1247789,28.6281367,28.8758897,30.6263973,29.8744306,30.1259055,27.8726262,28.1259446,30.8741594,..,..
1,Albania,ALB,Land Surface Temperature,EN.LND.LTMP.DC,19.0624193,19.5603627,19.8123073,19.8120257,19.3167489,19.9392779,19.0618451,20.3114606,19.6873912,19.9359187,20.3149516,19.4389756,..,..
2,Algeria,DZA,Land Surface Temperature,EN.LND.LTMP.DC,38.8769805,37.8767998,38.0630928,38.6280513,38.1877112,37.6879212,38.4380335,37.6875988,37.874857,38.3769659,38.625905,38.6265931,..,..
3,Andorra,AND,Land Surface Temperature,EN.LND.LTMP.DC,8.53112755,11.72457,10.7851562,8.82637681,9.53013984,10.9608562,11.3370428,11.0918618,9.2744517,11.4595388,11.4030152,10.2783194,..,..
4,Angola,AGO,Land Surface Temperature,EN.LND.LTMP.DC,29.8113382,29.3119114,29.9370658,30.1872676,29.6872372,29.9367326,30.0622152,30.312361,30.0623632,30.3114805,30.0622529,30.3124645,..,..

In [ ]:
#Dernières lignes
df_wbg_temperature.tail(6)

,Country Name,Country Code,Series Name,Series Code,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
192,Zimbabwe,ZWE,Land Surface Temperature,EN.LND.LTMP.DC,31.6876496,31.8127066,32.8124978,32.6877371,31.6870377,33.1877084,33.1871179,30.4378471,32.6869318,33.8128838,32.4368735,31.4370772,..,..
193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,Data from database: Environment Social and Gov...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,Last Updated: 07/30/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Bilan :
*   5 dernières lignes vides (NaN) : à supprimer
*   193 pays différents
*   Pas de colonne avec NaN
*   Pas d'autre ligne avec NaN
*   pk : "country code" ou "country name"

### 2.7.2 - Nettoyage

In [ ]:
#Suppression des colonnes et lignes superflues
df_wbg_temperature_c = df_wbg_temperature.drop(columns=['Series Code'])
df_wbg_temperature_c = df_wbg_temperature_c .dropna(subset=['Country Code'])
df_wbg_temperature_c.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193 entries, 0 to 192
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   193 non-null    object
 1   Country Code   193 non-null    object
 2   Series Name    193 non-null    object
 3   2010 [YR2010]  193 non-null    object
 4   2011 [YR2011]  193 non-null    object
 5   2012 [YR2012]  193 non-null    object
 6   2013 [YR2013]  193 non-null    object
 7   2014 [YR2014]  193 non-null    object
 8   2015 [YR2015]  193 non-null    object
 9   2016 [YR2016]  193 non-null    object
 10  2017 [YR2017]  193 non-null    object
 11  2018 [YR2018]  193 non-null    object
 12  2019 [YR2019]  193 non-null    object
 13  2020 [YR2020]  193 non-null    object
 14  2021 [YR2021]  193 non-null    object
 15  2022 [YR2022]  193 non-null    object
 16  2023 [YR2023]  193 non-null    object
dtypes: object(17)
memory usage: 27.1+ KB

### 2.7.3 - Mise en forme

In [ ]:
#Mise en forme tableau
df_wbg_temperature_t = df_wbg_temperature_c.melt(id_vars=['Country Code','Country Name','Series Name'], var_name='Année brute', value_name='Valeur')
df_wbg_temperature_t[['Année', 'Code Année']] = df_wbg_temperature_t['Année brute'].str.split(' ', expand=True)
df_wbg_temperature_t

,Country Code,Country Name,Series Name,Année brute,Valeur,Année,Code Année
0,AFG,Afghanistan,Land Surface Temperature,2010 [YR2010],29.6243831,2010,[YR2010]
1,ALB,Albania,Land Surface Temperature,2010 [YR2010],19.0624193,2010,[YR2010]
2,DZA,Algeria,Land Surface Temperature,2010 [YR2010],38.8769805,2010,[YR2010]
3,AND,Andorra,Land Surface Temperature,2010 [YR2010],8.53112755,2010,[YR2010]
4,AGO,Angola,Land Surface Temperature,2010 [YR2010],29.8113382,2010,[YR2010]
...,...,...,...,...,...,...,...
2697,VEN,"Venezuela, RB",Land Surface Temperature,2023 [YR2023],..,2023,[YR2023]
2698,VNM,Viet Nam,Land Surface Temperature,2023 [YR2023],..,2023,[YR2023]
2699,YEM,"Yemen, Rep.",Land Surface Temperature,2023 [YR2023],..,2023,[YR2023]
2700,ZMB,Zambia,Land Surface Temperature,2023 [YR2023],..,2023,[YR2023]
2701,ZWE,Zimbabwe,Land Surface Temperature,2023 [YR2023],..,2023,[YR2023]

In [ ]:
#Mise en forme pivot
df_wbg_temperature_p = df_wbg_temperature_t.pivot_table(index=['Country Code','Country Name','Année'], columns='Series Name', values='Valeur', aggfunc='sum').reset_index()
df_wbg_temperature_p

Series Name Country Code Country Name Année Land Surface Temperature
0                    AFG  Afghanistan  2010               29.6243831
1                    AFG  Afghanistan  2011               29.1250018
2                    AFG  Afghanistan  2012               27.3746873
3                    AFG  Afghanistan  2013               29.1247789
4                    AFG  Afghanistan  2014               28.6281367
...                  ...          ...   ...                      ...
2697                 ZWE     Zimbabwe  2019               33.8128838
2698                 ZWE     Zimbabwe  2020               32.4368735
2699                 ZWE     Zimbabwe  2021               31.4370772
2700                 ZWE     Zimbabwe  2022                       ..
2701                 ZWE     Zimbabwe  2023                       ..

[2702 rows x 4 columns]

In [ ]:
#Mise en forme finale
df_wbg_temperature_f = df_wbg_temperature_p.rename(columns={'Country Code':'Id pays','Country Name':'Pays','Land Surface Temperature':'Temp surface terrestre (°C)'})
df_wbg_temperature_f.columns.name = None
df_wbg_temperature_f = df_wbg_temperature_f.replace('..', np.nan)
df_wbg_temperature_f = df_wbg_temperature_f.dropna()
df_wbg_temperature_f

     Id pays         Pays Année Temp surface terrestre (°C)
0        AFG  Afghanistan  2010                  29.6243831
1        AFG  Afghanistan  2011                  29.1250018
2        AFG  Afghanistan  2012                  27.3746873
3        AFG  Afghanistan  2013                  29.1247789
4        AFG  Afghanistan  2014                  28.6281367
...      ...          ...   ...                         ...
2695     ZWE     Zimbabwe  2017                  30.4378471
2696     ZWE     Zimbabwe  2018                  32.6869318
2697     ZWE     Zimbabwe  2019                  33.8128838
2698     ZWE     Zimbabwe  2020                  32.4368735
2699     ZWE     Zimbabwe  2021                  31.4370772

[2296 rows x 4 columns]

In [ ]:
#Caractéristiques
df_wbg_temperature_f.info()
print("\n")
df_wbg_temperature_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 2296 entries, 0 to 2699
Data columns (total 4 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Id pays                      2296 non-null   object
 1   Pays                         2296 non-null   object
 2   Année                        2296 non-null   object
 3   Temp surface terrestre (°C)  2296 non-null   object
dtypes: object(4)
memory usage: 154.2+ KB

       Id pays         Pays Année Temp surface terrestre (°C)
count     2296         2296  2296                        2296
unique     192          192    12                        2296
top        AFG  Afghanistan  2010                  31.4370772
freq        12           12   192                           1

## 2.8 - Analyse exploratoire df_cepii_distance

### 2.8.1 - Evaluation du dataset

In [ ]:
#Caractéristiques
df_cepii_distance.info()
print("\n")
df_cepii_distance.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50176 entries, 0 to 50175
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iso_o          50176 non-null  object
 1   iso_d          50176 non-null  object
 2   contig         50176 non-null  int64
 3   comlang_off    50176 non-null  int64
 4   comlang_ethno  50176 non-null  int64
 5   colony         50176 non-null  int64
 6   comcol         50176 non-null  int64
 7   curcol         50176 non-null  int64
 8   col45          50176 non-null  int64
 9   smctry         50176 non-null  int64
 10  dist           50176 non-null  object
 11  distcap        50176 non-null  object
 12  distw          50176 non-null  object
 13  distwces       50176 non-null  object
dtypes: int64(8), object(6)
memory usage: 5.4+ MB

,iso_o,iso_d,contig,comlang_off,comlang_ethno,colony,comcol,curcol,col45,smctry,dist,distcap,distw,distwces
count,50176,50176,50176.000000,50176.000000,50176.000000,50176.000000,50176.000000,50176.000000,50176.000000,50176.000000,50176,50176,50176,50176
unique,224,224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25135,25135,25526,25606
top,ABW,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10911,55","10911,55",.,.
freq,224,224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6,2215,2215
mean,NaN,NaN,0.012277,0.174386,0.169165,0.009606,0.117307,0.001276,0.006218,0.007992,NaN,NaN,NaN,NaN
std,NaN,NaN,0.110120,0.379445,0.374901,0.097540,0.321789,0.035692,0.078610,0.089040,NaN,NaN,NaN,NaN
min,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_cepii_distance.head()

,iso_o,iso_d,contig,comlang_off,comlang_ethno,colony,comcol,curcol,col45,smctry,dist,distcap,distw,distwces
0,ABW,ABW,0,0,0,0,0,0,0,0,"5,225315","5,225315","25,09354","23,04723"
1,ABW,AFG,0,0,0,0,0,0,0,0,"13257,81","13257,81","13168,22","13166,37"
2,ABW,AGO,0,0,0,0,0,0,0,0,"9516,913","9516,913","9587,316","9584,193"
3,ABW,AIA,0,0,1,0,0,0,0,0,"983,2682","983,2682","976,8974","976,8916"
4,ABW,ALB,0,0,0,0,0,0,0,0,"9091,742","9091,742","9091,576","9091,466"

In [ ]:
#Dernières lignes
df_cepii_distance.tail()

,iso_o,iso_d,contig,comlang_off,comlang_ethno,colony,comcol,curcol,col45,smctry,dist,distcap,distw,distwces
50171,ZWE,YUG,0,0,0,0,0,0,0,0,"7056,402","7056,402","7046,432","7042,83"
50172,ZWE,ZAF,1,1,1,0,0,0,0,0,"2186,206","926,1743","1258,552","1101,438"
50173,ZWE,ZAR,0,0,0,0,0,0,0,0,"2283,061","2283,061","1930,976","1719,147"
50174,ZWE,ZMB,1,1,1,0,1,0,0,0,"396,8041","396,8041","583,7954","525,0734"
50175,ZWE,ZWE,0,0,0,0,0,0,0,0,"235,1193","235,1193","199,8205","67,83789"

Bilan :
*   Pas de colonne ni de ligne avec NaN
*   224 pays différents
*   Pas de pk native : "iso_o"&"iso_d"

### 2.8.2 - Nettoyage

In [ ]:
#Conservation des distances avec la France
df_cepii_distance_france = df_cepii_distance[df_cepii_distance['iso_o'] == 'FRA'].reset_index(drop=True)
df_cepii_distance_france.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iso_o          224 non-null    object
 1   iso_d          224 non-null    object
 2   contig         224 non-null    int64
 3   comlang_off    224 non-null    int64
 4   comlang_ethno  224 non-null    int64
 5   colony         224 non-null    int64
 6   comcol         224 non-null    int64
 7   curcol         224 non-null    int64
 8   col45          224 non-null    int64
 9   smctry         224 non-null    int64
 10  dist           224 non-null    object
 11  distcap        224 non-null    object
 12  distw          224 non-null    object
 13  distwces       224 non-null    object
dtypes: int64(8), object(6)
memory usage: 24.6+ KB

In [ ]:
#Suppression des colonnes superflues
df_cepii_distance_c = df_cepii_distance_france.drop(columns=['iso_o','contig','comlang_off','comlang_ethno','colony','comcol','curcol','col45','smctry','dist','distcap','distwces'])
df_cepii_distance_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   iso_d   224 non-null    object
 1   distw   224 non-null    object
dtypes: object(2)
memory usage: 3.6+ KB

### 2.8.3 - Mise en forme

In [ ]:
#Mise en forme finale
df_cepii_distance_f = df_cepii_distance_c.rename(columns={'iso_d':'Id pays','distw':'Distance avec la France (km)'})
df_cepii_distance_f = df_cepii_distance_f.dropna()
df_cepii_distance_f

    Id pays Distance avec la France (km)
0       ABW                     7716,752
1       AFG                     5500,665
2       AGO                     6384,805
3       AIA                     6743,427
4       ALB                     1499,451
..      ...                          ...
219     YUG                     1429,045
220     ZAF                     8769,679
221     ZAR                     6036,588
222     ZMB                     7236,737
223     ZWE                     7771,569

[224 rows x 2 columns]

In [ ]:
#Caractéristiques
df_cepii_distance_f.info()
print("\n")
df_cepii_distance_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Id pays                       224 non-null    object
 1   Distance avec la France (km)  224 non-null    object
dtypes: object(2)
memory usage: 3.6+ KB

       Id pays Distance avec la France (km)
count      224                          224
unique     224                          220
top        ABW                            .
freq         1                            5

## 2.9 - Analyse exploratoire df_cepii_langues

### 2.9.1 - Evaluation dataset

In [ ]:
#Caractéristiques
df_cepii_langue.info()
print("\n")
df_cepii_langue.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   iso2              237 non-null    object
 1   iso3              238 non-null    object
 2   cnum              238 non-null    int64
 3   country           238 non-null    object
 4   pays              238 non-null    object
 5   area              238 non-null    int64
 6   dis_int           238 non-null    float64
 7   landlocked        238 non-null    int64
 8   continent         238 non-null    object
 9   city_en           238 non-null    object
 10  city_fr           238 non-null    object
 11  lat               238 non-null    float64
 12  lon               238 non-null    float64
 13  cap               238 non-null    int64
 14  maincity          238 non-null    int64
 15  citynum           238 non-null    object
 16  langoff_1         238 non-null    object
 17  langoff_2         238 non-null    object
 18  langoff_3         238 non-null    object
 19  lang20_1          238 non-null    object
 20  lang20_2          238 non-null    object
 21  lang20_3          238 non-null    object
 22  lang20_4          238 non-null    object
 23  lang9_1           238 non-null    object
 24  lang9_2           238 non-null    object
 25  lang9_3           238 non-null    object
 26  lang9_4           238 non-null    object
 27  colonizer1        238 non-null    object
 28  colonizer2        238 non-null    object
 29  colonizer3        238 non-null    object
 30  colonizer4        238 non-null    object
 31  short_colonizer1  238 non-null    object
 32  short_colonizer2  238 non-null    object
 33  short_colonizer3  238 non-null    object
dtypes: float64(3), int64(5), object(26)
memory usage: 63.3+ KB

,iso2,iso3,cnum,country,pays,area,dis_int,landlocked,continent,city_en,city_fr,lat,lon,cap,maincity,citynum,langoff_1,langoff_2,langoff_3,lang20_1,lang20_2,lang20_3,lang20_4,lang9_1,lang9_2,lang9_3,lang9_4,colonizer1,colonizer2,colonizer3,colonizer4,short_colonizer1,short_colonizer2,short_colonizer3
count,237,238,238.000000,238,238,2.380000e+02,238.000000,238.000000,238,238,238,238.000000,238.000000,238.000000,238.000000,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238
unique,224,225,NaN,225,225,NaN,NaN,NaN,6,235,235,NaN,NaN,NaN,NaN,26,69,20,10,103,67,23,4,63,21,6,2,15,18,5,2,22,7,2
top,AU,AUS,NaN,Australia,Australie,NaN,NaN,NaN,Africa,Victoria,Victoria,NaN,NaN,NaN,NaN,25,English,.,.,English,.,.,.,.,.,.,.,GBR,.,.,.,.,.,.
freq,2,2,NaN,2,2,NaN,NaN,NaN,61,2,2,NaN,NaN,NaN,NaN,161,70,180,227,50,123,203,235,162,216,233,237,87,196,230,235,200,230,237
mean,NaN,NaN,436.298319,NaN,NaN,7.581392e+05,203.882936,0.159664,NaN,NaN,NaN,15.979471,14.996275,0.995798,0.945378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,256.734227,NaN,NaN,2.056226e+06,256.833913,0.367066,NaN,NaN,NaN,25.759714,74.270938,0.234168,0.227720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,4.000000,NaN,NaN,7.000000e+00,0.995137,0.000000,NaN,NaN,NaN,-66.666660,-176.200000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,212.500000,NaN,NaN,9.551250e+03,36.745795,0.000000,NaN,NaN,NaN,0.233333,-50.777498,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,432.000000,NaN,NaN,1.058540e+05,122.360900,0.000000,NaN,NaN,NaN,15.250000,16.733335,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,657.750000,NaN,NaN,5.385482e+05,275.997450,0.000000,NaN,NaN,NaN,37.987500,50.445840,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,931.000000,NaN,NaN,1.707540e+07,1554.244000,1.000000,NaN,NaN,NaN,64.183330,179.200000,2.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_cepii_langue.head()

,iso2,iso3,cnum,country,pays,area,dis_int,landlocked,continent,city_en,city_fr,lat,lon,cap,maincity,citynum,langoff_1,langoff_2,langoff_3,lang20_1,lang20_2,lang20_3,lang20_4,lang9_1,lang9_2,lang9_3,lang9_4,colonizer1,colonizer2,colonizer3,colonizer4,short_colonizer1,short_colonizer2,short_colonizer3
0,AW,ABW,533,Aruba,Aruba,193,5.225315,0,America,Oranjestad,Oranjestad,12.550000,-70.10000,1,1,2,Dutch,Spanish,.,Dutch,English,Papiamento,.,.,.,.,.,NLD,.,.,.,.,.,.
1,AF,AFG,4,Afghanistan,Afghanistan,652225,303.761400,1,Asia,Kabul,Kaboul,34.516670,69.20000,1,1,25,Persian,.,.,Persian,Pashtu,.,.,Hazaragi,Uzbek,.,.,.,.,.,.,GBR,.,.
2,AO,AGO,24,Angola,Angola,1246700,419.966600,0,Africa,Luanda,Luanda,-8.833333,13.25000,1,1,25,Portuguese,.,.,Portuguese,Umbundu,Mbundu Loanda,.,Kongo,.,.,.,PRT,.,.,.,.,.,.
3,AI,AIA,660,Anguilla,Anguilla,102,3.798690,0,America,The Valley,The Valley,18.216670,-63.06667,1,1,2,English,.,.,English,Leeward Caribbean Creole English,.,.,.,.,.,.,GBR,.,.,.,.,.,.
4,AL,ALB,8,Albania,Albanie,28748,63.773110,0,Europe,Tirana,Tirana,41.333330,19.81667,1,1,25,Albanian,.,.,Albanian,.,.,.,.,.,.,.,TUR,.,.,.,.,.,.

### 2.9.2 - Nettoyage

In [ ]:
#Identification erreur colonne "iso2"
df_cepii_langue[df_cepii_langue['iso2'].isnull()]

,iso2,iso3,cnum,country,pays,area,dis_int,landlocked,continent,city_en,city_fr,lat,lon,cap,maincity,citynum,langoff_1,langoff_2,langoff_3,lang20_1,lang20_2,lang20_3,lang20_4,lang9_1,lang9_2,lang9_3,lang9_4,colonizer1,colonizer2,colonizer3,colonizer4,short_colonizer1,short_colonizer2,short_colonizer3
149,NaN,NAM,516,Namibia,Namibie,825518,341.741,0,Africa,Windhoek,Windhoeck,-22.56667,17.1,1,1,25,English,.,.,English,Kwanyama,.,.,Afrikaans,.,.,.,DEU,ZAF,.,.,.,.,.

In [ ]:
#Correction erreur colonne "iso2" (la valeur "Na" pour la Namibi a été interprétée comme une donnée absente "Not Available")
df_cepii_langue.loc[df_cepii_langue['iso2'].isnull(), 'iso2'] = 'NA'

In [ ]:
#Caractéristiques
df_cepii_langue.info()
print("\n")
df_cepii_langue.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   iso2              238 non-null    object
 1   iso3              238 non-null    object
 2   cnum              238 non-null    int64
 3   country           238 non-null    object
 4   pays              238 non-null    object
 5   area              238 non-null    int64
 6   dis_int           238 non-null    float64
 7   landlocked        238 non-null    int64
 8   continent         238 non-null    object
 9   city_en           238 non-null    object
 10  city_fr           238 non-null    object
 11  lat               238 non-null    float64
 12  lon               238 non-null    float64
 13  cap               238 non-null    int64
 14  maincity          238 non-null    int64
 15  citynum           238 non-null    object
 16  langoff_1         238 non-null    object
 17  langoff_2         238 non-null    object
 18  langoff_3         238 non-null    object
 19  lang20_1          238 non-null    object
 20  lang20_2          238 non-null    object
 21  lang20_3          238 non-null    object
 22  lang20_4          238 non-null    object
 23  lang9_1           238 non-null    object
 24  lang9_2           238 non-null    object
 25  lang9_3           238 non-null    object
 26  lang9_4           238 non-null    object
 27  colonizer1        238 non-null    object
 28  colonizer2        238 non-null    object
 29  colonizer3        238 non-null    object
 30  colonizer4        238 non-null    object
 31  short_colonizer1  238 non-null    object
 32  short_colonizer2  238 non-null    object
 33  short_colonizer3  238 non-null    object
dtypes: float64(3), int64(5), object(26)
memory usage: 63.3+ KB

,iso2,iso3,cnum,country,pays,area,dis_int,landlocked,continent,city_en,city_fr,lat,lon,cap,maincity,citynum,langoff_1,langoff_2,langoff_3,lang20_1,lang20_2,lang20_3,lang20_4,lang9_1,lang9_2,lang9_3,lang9_4,colonizer1,colonizer2,colonizer3,colonizer4,short_colonizer1,short_colonizer2,short_colonizer3
count,238,238,238.000000,238,238,2.380000e+02,238.000000,238.000000,238,238,238,238.000000,238.000000,238.000000,238.000000,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238,238
unique,225,225,NaN,225,225,NaN,NaN,NaN,6,235,235,NaN,NaN,NaN,NaN,26,69,20,10,103,67,23,4,63,21,6,2,15,18,5,2,22,7,2
top,AU,AUS,NaN,Australia,Australie,NaN,NaN,NaN,Africa,Victoria,Victoria,NaN,NaN,NaN,NaN,25,English,.,.,English,.,.,.,.,.,.,.,GBR,.,.,.,.,.,.
freq,2,2,NaN,2,2,NaN,NaN,NaN,61,2,2,NaN,NaN,NaN,NaN,161,70,180,227,50,123,203,235,162,216,233,237,87,196,230,235,200,230,237
mean,NaN,NaN,436.298319,NaN,NaN,7.581392e+05,203.882936,0.159664,NaN,NaN,NaN,15.979471,14.996275,0.995798,0.945378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,256.734227,NaN,NaN,2.056226e+06,256.833913,0.367066,NaN,NaN,NaN,25.759714,74.270938,0.234168,0.227720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,4.000000,NaN,NaN,7.000000e+00,0.995137,0.000000,NaN,NaN,NaN,-66.666660,-176.200000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,212.500000,NaN,NaN,9.551250e+03,36.745795,0.000000,NaN,NaN,NaN,0.233333,-50.777498,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,432.000000,NaN,NaN,1.058540e+05,122.360900,0.000000,NaN,NaN,NaN,15.250000,16.733335,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,657.750000,NaN,NaN,5.385482e+05,275.997450,0.000000,NaN,NaN,NaN,37.987500,50.445840,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,931.000000,NaN,NaN,1.707540e+07,1554.244000,1.000000,NaN,NaN,NaN,64.183330,179.200000,2.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Premières lignes
df_cepii_langue.head()

,iso2,iso3,cnum,country,pays,area,dis_int,landlocked,continent,city_en,city_fr,lat,lon,cap,maincity,citynum,langoff_1,langoff_2,langoff_3,lang20_1,lang20_2,lang20_3,lang20_4,lang9_1,lang9_2,lang9_3,lang9_4,colonizer1,colonizer2,colonizer3,colonizer4,short_colonizer1,short_colonizer2,short_colonizer3
0,AW,ABW,533,Aruba,Aruba,193,5.225315,0,America,Oranjestad,Oranjestad,12.550000,-70.10000,1,1,2,Dutch,Spanish,.,Dutch,English,Papiamento,.,.,.,.,.,NLD,.,.,.,.,.,.
1,AF,AFG,4,Afghanistan,Afghanistan,652225,303.761400,1,Asia,Kabul,Kaboul,34.516670,69.20000,1,1,25,Persian,.,.,Persian,Pashtu,.,.,Hazaragi,Uzbek,.,.,.,.,.,.,GBR,.,.
2,AO,AGO,24,Angola,Angola,1246700,419.966600,0,Africa,Luanda,Luanda,-8.833333,13.25000,1,1,25,Portuguese,.,.,Portuguese,Umbundu,Mbundu Loanda,.,Kongo,.,.,.,PRT,.,.,.,.,.,.
3,AI,AIA,660,Anguilla,Anguilla,102,3.798690,0,America,The Valley,The Valley,18.216670,-63.06667,1,1,2,English,.,.,English,Leeward Caribbean Creole English,.,.,.,.,.,.,GBR,.,.,.,.,.,.
4,AL,ALB,8,Albania,Albanie,28748,63.773110,0,Europe,Tirana,Tirana,41.333330,19.81667,1,1,25,Albanian,.,.,Albanian,.,.,.,.,.,.,.,TUR,.,.,.,.,.,.

In [ ]:
#Dernières lignes
df_cepii_langue.tail()

,iso2,iso3,cnum,country,pays,area,dis_int,landlocked,continent,city_en,city_fr,lat,lon,cap,maincity,citynum,langoff_1,langoff_2,langoff_3,lang20_1,lang20_2,lang20_3,lang20_4,lang9_1,lang9_2,lang9_3,lang9_4,colonizer1,colonizer2,colonizer3,colonizer4,short_colonizer1,short_colonizer2,short_colonizer3
233,ZA,ZAF,711,South Africa,Afrique du Sud,1219912,415.4302,0,Africa,Pretoria,Pretoria,-25.73000,28.22000,1,0,25,English,.,.,Zoulou,Xhosa,English,.,Afrikaans,Shoto,.,.,GBR,NLD,.,.,.,.,.
234,ZA,ZAF,711,South Africa,Afrique du Sud,1219912,415.4302,0,Africa,Cape Town,Le Cap,-33.93333,18.46667,2,1,25,English,.,.,Zoulou,Xhosa,English,.,Afrikaans,Shoto,.,.,GBR,NLD,.,.,.,.,.
235,ZR,ZAR,180,Congo (Democratic Republic of the),Congo. Rép. dém. du,2345410,576.0275,0,Africa,Kinshasa,Kinshasa,-4.30000,15.30000,1,1,25,French,.,.,Swahili,Lingala,.,.,Kikongo,Luba-Kasai,French,.,BEL,.,.,.,.,.,.
236,ZM,ZMB,894,Zambia,Zambie,752614,326.3022,1,Africa,Lusaka,Lusaka,-15.46667,28.26667,1,1,25,English,.,.,English,.,.,.,Nyanja,Tonga,.,.,GBR,.,.,.,.,.,.
237,ZW,ZWE,716,Zimbabwe,Zimbabwe,390759,235.1193,1,Africa,Harare,Harare,-17.83333,31.05000,1,1,25,English,.,.,Shona,English,.,.,Ndebele,.,.,.,GBR,.,.,.,.,.,.

In [ ]:
#Suppression des colonnes superflues
df_cepii_langue_c =df_cepii_langue.drop(columns=['iso2','country','area','dis_int','landlocked','city_en','city_fr','lat','lon','cap','maincity','citynum','lang20_1','lang20_2','lang20_3','lang20_4','lang9_1','lang9_2','lang9_3','lang9_4','colonizer1','colonizer2','colonizer3','colonizer4','short_colonizer1','short_colonizer2','short_colonizer3'])
df_cepii_langue_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   iso3       238 non-null    object
 1   cnum       238 non-null    int64
 2   pays       238 non-null    object
 3   continent  238 non-null    object
 4   langoff_1  238 non-null    object
 5   langoff_2  238 non-null    object
 6   langoff_3  238 non-null    object
dtypes: int64(1), object(6)
memory usage: 13.1+ KB

### 2.9.3 - Mise en forme

In [ ]:
#Mise en forme finale
df_cepii_langue_f = df_cepii_langue_c.rename(columns={'iso3':'Id pays','cnum':'Code pays','pays':'Pays','continent':'Continent'})
df_cepii_langue_f = df_cepii_langue_f.replace('.', '')
df_cepii_langue_f = df_cepii_langue_f.dropna()
df_cepii_langue_f

,Id pays,Code pays,Pays,Continent,langoff_1,langoff_2,langoff_3
0,ABW,533,Aruba,America,Dutch,Spanish,
1,AFG,4,Afghanistan,Asia,Persian,,
2,AGO,24,Angola,Africa,Portuguese,,
3,AIA,660,Anguilla,America,English,,
4,ALB,8,Albanie,Europe,Albanian,,
...,...,...,...,...,...,...,...
233,ZAF,711,Afrique du Sud,Africa,English,,
234,ZAF,711,Afrique du Sud,Africa,English,,
235,ZAR,180,Congo. Rép. dém. du,Africa,French,,
236,ZMB,894,Zambie,Africa,English,,
237,ZWE,716,Zimbabwe,Africa,English,,

In [ ]:
#Caractéritiques
df_cepii_langue_f.info()
print("\n")
df_cepii_langue_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id pays    238 non-null    object
 1   Code pays  238 non-null    int64
 2   Pays       238 non-null    object
 3   Continent  238 non-null    object
 4   langoff_1  238 non-null    object
 5   langoff_2  238 non-null    object
 6   langoff_3  238 non-null    object
dtypes: int64(1), object(6)
memory usage: 13.1+ KB

       Id pays   Code pays       Pays Continent langoff_1 langoff_2 langoff_3
count      238  238.000000        238       238       238       238       238
unique     225         NaN        225         6        69        20        10
top        AUS         NaN  Australie    Africa   English
freq         2         NaN          2        61        70       180       227
mean       NaN  436.298319        NaN       NaN       NaN       NaN       NaN
std        NaN  256.734227        NaN       NaN       NaN       NaN       NaN
min        NaN    4.000000        NaN       NaN       NaN       NaN       NaN
25%        NaN  212.500000        NaN       NaN       NaN       NaN       NaN
50%        NaN  432.000000        NaN       NaN       NaN       NaN       NaN
75%        NaN  657.750000        NaN       NaN       NaN       NaN       NaN
max        NaN  931.000000        NaN       NaN       NaN       NaN       NaN

In [ ]:
#Identifier les 'Id pays' en donblon
df_cepii_langue_f[df_cepii_langue_f['Id pays'].duplicated(keep=False)]

,Id pays,Code pays,Pays,Continent,langoff_1,langoff_2,langoff_3
12,AUS,36,Australie,Pacific,English,,
13,AUS,36,Australie,Pacific,English,,
18,BEN,204,Bénin,Africa,French,,
19,BEN,204,Bénin,Africa,French,,
29,BOL,68,Bolivie,America,Spanish,Quecha,Aymara
30,BOL,68,Bolivie,America,Spanish,Quecha,Aymara
31,BRA,76,Brésil,America,Portuguese,,
32,BRA,76,Brésil,America,Portuguese,,
38,CAN,124,Canada,America,English,French,
39,CAN,124,Canada,America,English,French,
44,CIV,384,Côte d'Ivoire,Africa,French,,
45,CIV,384,Côte d'Ivoire,Africa,French,,
58,DEU,276,Allemagne,Europe,German,,
59,DEU,276,Allemagne,Europe,German,,
110,KAZ,398,Kazakstan,Asia,Kazakh,Russian,
111,KAZ,398,Kazakstan,Asia,Kazakh,Russian,
153,NGA,566,Nigéria,Africa,English,,
154,NGA,566,Nigéria,Africa,English,,
212,TUR,792,Turquie,Europe,Turkish,,
213,TUR,792,Turquie,Europe,Turkish,,
216,TZA,834,Tanzanie,Africa,English,Swahili,
217,TZA,834,Tanzanie,Africa,English,Swahili,
221,USA,842,Etats-Unis d'Amérique,America,English,,
222,USA,842,Etats-Unis d'Amérique,America,English,,
233,ZAF,711,Afrique du Sud,Africa,English,,
234,ZAF,711,Afrique du Sud,Africa,English,,

In [ ]:
#Supprimer les 'Id pays' en doublon
df_cepii_langue_f = df_cepii_langue_f.drop_duplicates(subset='Id pays', keep='first')
df_cepii_langue_f.info()
print("\n")
df_cepii_langue_f.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 225 entries, 0 to 237
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id pays    225 non-null    object
 1   Code pays  225 non-null    int64
 2   Pays       225 non-null    object
 3   Continent  225 non-null    object
 4   langoff_1  225 non-null    object
 5   langoff_2  225 non-null    object
 6   langoff_3  225 non-null    object
dtypes: int64(1), object(6)
memory usage: 14.1+ KB

       Id pays   Code pays   Pays Continent langoff_1 langoff_2 langoff_3
count      225  225.000000    225       225       225       225       225
unique     225         NaN    225         6        69        20        10
top        ABW         NaN  Aruba    Africa   English
freq         1         NaN      1        56        64       171       215
mean       NaN  437.902222    NaN       NaN       NaN       NaN       NaN
std        NaN  254.179526    NaN       NaN       NaN       NaN       NaN
min        NaN    4.000000    NaN       NaN       NaN       NaN       NaN
25%        NaN  218.000000    NaN       NaN       NaN       NaN       NaN
50%        NaN  440.000000    NaN       NaN       NaN       NaN       NaN
75%        NaN  654.000000    NaN       NaN       NaN       NaN       NaN
max        NaN  931.000000    NaN       NaN       NaN       NaN       NaN

# Etape 3 - Dataframes intermédiaires

## 3.1 - Liaison FAO

In [ ]:
#Clés
df_fao_dispo_f['Clé FAO'] = df_fao_dispo_f['Code pays'].astype(str) + '-' + df_fao_dispo_f['Année'].astype(str)
df_fao_healthydiet_f['Clé FAO'] = df_fao_healthydiet_f['Code pays'].astype(str) + '-' + df_fao_healthydiet_f['Année'].astype(str)
df_fao_PIB_f['Clé FAO'] = df_fao_PIB_f['Code pays'].astype(str) + '-' + df_fao_PIB_f['Année'].astype(str)
df_fao_population_f['Clé FAO'] = df_fao_population_f['Code pays'].astype(str) + '-' + df_fao_population_f['Année'].astype(str)
df_fao_stability_f['Clé FAO'] = df_fao_stability_f['Code pays'].astype(str) + '-' + df_fao_stability_f['Année'].astype(str)

In [ ]:
#Liaisons
df_1 = pd.merge(df_fao_healthydiet_f,df_fao_dispo_f[['Clé FAO','Dispo viande volaille (kg/personne/an)','Import viande volaille (1000 t)','Production viande volaille (1000 t)','Dispo intérieure viande volaille (1000 t)']], on='Clé FAO', how='left')
df_2 = pd.merge(df_1,df_fao_PIB_f[['Clé FAO','PIB/hab ($ PPA internationaux constants de 2021)']], on='Clé FAO', how='left')
df_3 = pd.merge(df_2, df_fao_population_f[['Clé FAO','Pop rurale (pour 1000)','Pop urbaine (pour 1000)','Pop totale (pour 1000)']], on='Clé FAO', how='left')
df_fao = pd.merge(df_3, df_fao_stability_f[['Clé FAO','Indice stabilité politique']], on='Clé FAO', how='left')

In [ ]:
#Suppression 'Clé_fao'
df_fao = df_fao.drop(columns=['Clé FAO'])
df_fao = df_fao.dropna()
df_fao

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million),Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),Production viande volaille (1000 t),Dispo intérieure viande volaille (1000 t),PIB/hab ($ PPA internationaux constants de 2021),Pop rurale (pour 1000),Pop urbaine (pour 1000),Pop totale (pour 1000),Indice stabilité politique
0,Afrique du Sud,710,2017,35.0,36.71,514.0,1665.0,2115.0,14591.0,19369.002,37348.154,57635.162,-0.28
1,Afrique du Sud,710,2018,35.3,38.02,515.0,1762.0,2228.0,14571.0,19311.652,38086.769,58613.000,-0.24
2,Afrique du Sud,710,2019,35.9,37.72,488.0,1816.0,2247.0,14370.0,19244.858,38820.239,59587.885,-0.28
3,Afrique du Sud,710,2020,37.4,37.32,425.0,1887.0,2260.0,13267.0,19170.340,39550.889,60562.381,-0.25
4,Afrique du Sud,710,2021,37.6,36.41,372.0,1917.0,2239.0,13711.0,19088.162,40277.814,61502.603,-0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,Éthiopie,231,2018,65.8,0.62,0.0,74.0,70.0,2311.0,85207.113,22327.769,112664.152,-1.27
1370,Éthiopie,231,2019,66.4,0.48,1.0,58.0,56.0,2438.0,86759.295,23376.340,115737.383,-1.30
1371,Éthiopie,231,2020,67.9,0.54,0.0,68.0,64.0,2517.0,88295.647,24463.423,118917.671,-1.75
1372,Éthiopie,231,2021,70.8,0.40,1.0,49.0,48.0,2588.0,89813.744,25589.582,122138.588,-2.18
1373,Éthiopie,231,2022,71.6,0.45,0.0,56.0,56.0,2656.0,91310.183,26755.042,125384.287,-2.07

In [ ]:
#Caractéristiques
df_fao.info()
print("\n")
df_fao.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 883 entries, 0 to 1373
Data columns (total 13 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Pays                                                 883 non-null    object
 1   Code pays                                            883 non-null    int64
 2   Année                                                883 non-null    int64
 3   Pop sans moyen de se nourrir sainement (en million)  883 non-null    float64
 4   Dispo viande volaille (kg/personne/an)               883 non-null    float64
 5   Import viande volaille (1000 t)                      883 non-null    float64
 6   Production viande volaille (1000 t)                  883 non-null    float64
 7   Dispo intérieure viande volaille (1000 t)            883 non-null    float64
 8   PIB/hab ($ PPA internationaux constants de 2021)     883 non-null    float64
 9   Pop rurale (pour 1000)                               883 non-null    float64
 10  Pop urbaine (pour 1000)                              883 non-null    float64
 11  Pop totale (pour 1000)                               883 non-null    float64
 12  Indice stabilité politique                           883 non-null    float64
dtypes: float64(10), int64(2), object(1)
memory usage: 96.6+ KB

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million),Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),Production viande volaille (1000 t),Dispo intérieure viande volaille (1000 t),PIB/hab ($ PPA internationaux constants de 2021),Pop rurale (pour 1000),Pop urbaine (pour 1000),Pop totale (pour 1000),Indice stabilité politique
count,883,883.000000,883.000000,883.00000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,8.830000e+02,883.000000
unique,149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Afrique du Sud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,430.045300,2019.515289,15.55957,22.909751,90.113250,714.271801,678.245753,25541.484711,17977.875707,21279.755426,3.979403e+04,-0.055821
std,NaN,248.201609,1.706511,65.15735,17.448917,179.192168,2287.432413,1889.529909,23838.678982,76115.225678,51319.139094,1.238485e+05,0.839276
min,NaN,8.000000,2017.000000,0.00000,0.400000,0.000000,0.000000,1.000000,1253.000000,0.000000,17.031000,4.670900e+01,-2.780000
25%,NaN,216.000000,2018.000000,0.20000,8.135000,3.000000,18.500000,44.000000,6668.500000,819.100500,1858.548000,2.891673e+03,-0.590000
50%,NaN,422.000000,2020.000000,1.50000,20.370000,21.000000,104.000000,138.000000,16746.000000,3375.656000,5695.930000,1.027912e+04,-0.020000
75%,NaN,646.000000,2021.000000,8.90000,32.310000,90.000000,463.000000,449.500000,37898.000000,12515.982000,18855.016500,3.315252e+04,0.650000
max,NaN,894.000000,2022.000000,804.90000,95.470000,1196.000000,23168.000000,19470.000000,136772.000000,905110.427000,506304.869000,1.425423e+06,1.620000

## 3.2 - Liaison WBG

In [ ]:
#Clés
df_wbg_index_f['Clé WBG'] = df_wbg_index_f['Id pays'] + '-' + df_wbg_index_f['Année'].astype(str)
df_wbg_temperature_f['Clé WBG'] = df_wbg_temperature_f['Id pays'] + '-' + df_wbg_temperature_f['Année'].astype(str)

In [ ]:
#Liaisons
df_wbg = pd.merge(df_wbg_temperature_f,df_wbg_index_f[['Clé WBG','Taux pop accès électricité','Indice perf log','Indice corruption','Indice état de droit']], on='Clé WBG', how='left')

In [ ]:
#Suppression 'Clé wbg'
df_wbg = df_wbg.drop(columns=['Clé WBG'])
df_wbg = df_wbg.dropna()
df_wbg

,Id pays,Pays,Année,Temp surface terrestre (°C),Taux pop accès électricité,Indice perf log,Indice corruption,Indice état de droit
0,AFG,Afghanistan,2010,29.6243831,42.7,2.24,-1.64539110660553,-1.87005805969238
2,AFG,Afghanistan,2012,27.3746873,69.1,2.3,-1.43037283420563,-1.6518931388855
4,AFG,Afghanistan,2014,28.6281367,89.5,2.069573,-1.36493408679962,-1.4377019405365
6,AFG,Afghanistan,2016,30.6263973,97.7,2.141282,-1.54022777080536,-1.52253365516663
8,AFG,Afghanistan,2018,30.1259055,93.4,1.95,-1.50287592411041,-1.68912386894226
...,...,...,...,...,...,...,...,...
2280,ZMB,Zambia,2018,30.5621355,40.2,2.53,-0.678888440132141,-0.358306616544724
2286,ZWE,Zimbabwe,2012,32.8124978,44,2.55,-1.38180339336395,-1.63018405437469
2288,ZWE,Zimbabwe,2014,31.6870377,32.3,2.33928,-1.40475881099701,-1.44185197353363
2290,ZWE,Zimbabwe,2016,33.1871179,42.5,2.082408,-1.28866481781006,-1.391646027565
2292,ZWE,Zimbabwe,2018,32.6869318,45.4,2.12,-1.24637961387634,-1.29305863380432

In [ ]:
#Conservation de l'année 2018 uniquement
df_wbg_2018 = df_wbg[df_wbg['Année'] == '2018'].reset_index(drop=True)
df_wbg_2018 = df_wbg_2018.rename(columns={'Temp surface terrestre (°C)':'Temp surface terrestre 2018 (°C)','Taux pop accès électricité':'Taux pop accès électricité 2018','Indice perf log':'Indice perf log 2018','Indice corruption':'Indice corruption 2018','Indice état de droit':'Indice état de droit 2018'})
df_wbg_2018 = df_wbg_2018.drop(columns=['Année'])
df_wbg_2018

,Id pays,Pays,Temp surface terrestre 2018 (°C),Taux pop accès électricité 2018,Indice perf log 2018,Indice corruption 2018,Indice état de droit 2018
0,AFG,Afghanistan,30.1259055,93.4,1.95,-1.50287592411041,-1.68912386894226
1,AGO,Angola,30.0623632,45.3,2.05,-1.19948387145996,-1.00106203556061
2,ALB,Albania,19.6873912,100,2.66,-0.546018898487091,-0.414752036333084
3,ARE,United Arab Emirates,43.6890475,100,3.96,1.11705148220062,0.774245142936707
4,ARG,Argentina,24.8753089,100,2.89,-0.0992739275097847,-0.219330430030823
...,...,...,...,...,...,...,...
152,VNM,Viet Nam,27.8129576,100,3.27,-0.511843025684357,-0.0354671441018581
153,YEM,"Yemen, Rep.",40.3114994,62,2.27,-1.65839195251465,-1.80602633953094
154,ZAF,South Africa,30.3751191,84.7,3.38,-0.136797428131104,-0.22182808816433
155,ZMB,Zambia,30.5621355,40.2,2.53,-0.678888440132141,-0.358306616544724
156,ZWE,Zimbabwe,32.6869318,45.4,2.12,-1.24637961387634,-1.29305863380432

In [ ]:
#Caractéritiques
df_wbg.info()
print("\n")
df_wbg.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 774 entries, 0 to 2292
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Id pays                      774 non-null    object
 1   Pays                         774 non-null    object
 2   Année                        774 non-null    object
 3   Temp surface terrestre (°C)  774 non-null    object
 4   Taux pop accès électricité   774 non-null    object
 5   Indice perf log              774 non-null    object
 6   Indice corruption            774 non-null    object
 7   Indice état de droit         774 non-null    object
dtypes: object(8)
memory usage: 70.6+ KB

,Id pays,Pays,Année,Temp surface terrestre (°C),Taux pop accès électricité,Indice perf log,Indice corruption,Indice état de droit
count,774,774,774,774,774,774,774,774
unique,164,164,5,774,294,494,774,774
top,AFG,Afghanistan,2014,32.6869318,100,2.58,-1.24637961387634,-1.29305863380432
freq,5,5,157,1,275,9,1,1

## 3.3 - Liaison CEPII

In [ ]:
#Liaisons
df_cepii = pd.merge(df_cepii_distance_f, df_cepii_langue_f[['Id pays','Code pays','Pays','Continent','langoff_1','langoff_2','langoff_3']], how='left', on='Id pays')

In [ ]:
#Suppression lignes NA
df_cepii = df_cepii.dropna()
df_cepii

,Id pays,Distance avec la France (km),Code pays,Pays,Continent,langoff_1,langoff_2,langoff_3
0,ABW,"7716,752",533,Aruba,America,Dutch,Spanish,
1,AFG,"5500,665",4,Afghanistan,Asia,Persian,,
2,AGO,"6384,805",24,Angola,Africa,Portuguese,,
3,AIA,"6743,427",660,Anguilla,America,English,,
4,ALB,"1499,451",8,Albanie,Europe,Albanian,,
...,...,...,...,...,...,...,...,...
219,YUG,"1429,045",891,Serbie et Monténégro (ex-Yougoslavie),Europe,Serbo-Croatian,,
220,ZAF,"8769,679",711,Afrique du Sud,Africa,English,,
221,ZAR,"6036,588",180,Congo. Rép. dém. du,Africa,French,,
222,ZMB,"7236,737",894,Zambie,Africa,English,,
223,ZWE,"7771,569",716,Zimbabwe,Africa,English,,

In [ ]:
#Caractéristiques
df_cepii.info()
print("\n")
df_cepii.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Id pays                       224 non-null    object
 1   Distance avec la France (km)  224 non-null    object
 2   Code pays                     224 non-null    int64
 3   Pays                          224 non-null    object
 4   Continent                     224 non-null    object
 5   langoff_1                     224 non-null    object
 6   langoff_2                     224 non-null    object
 7   langoff_3                     224 non-null    object
dtypes: int64(1), object(7)
memory usage: 14.1+ KB

,Id pays,Distance avec la France (km),Code pays,Pays,Continent,langoff_1,langoff_2,langoff_3
count,224,224,224.000000,224,224,224,224,224
unique,224,220,NaN,224,5,69,20,10
top,ABW,.,NaN,Aruba,Africa,English,,
freq,1,5,NaN,1,56,64,170,214
mean,NaN,NaN,438.696429,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,254.468842,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,217.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,441.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,655.250000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,931.000000,NaN,NaN,NaN,NaN,NaN

# Etape 4 - Création des variables calculées

## 4.1 - FAO : Taux de croissance annuel moyen du PIB entre 2017 et 2022

In [ ]:
#Tableau temporaire
df_pivot_pib = df_fao.pivot_table(index='Pays',columns='Année',values='PIB/hab ($ PPA internationaux constants de 2021)')

#Calcul du TCAM entre 2017 et 2022 : ((V_finale / V_initiale)^(1/n) - 1) * 100
n = 7
df_pivot_pib['TCAM PIB 2017-2022'] = ((df_pivot_pib[2022] / df_pivot_pib[2017])**(1/n) - 1) * 100

#Ajout à df_fao
df_fao = pd.merge(df_fao,df_pivot_pib[['TCAM PIB 2017-2022']], on='Pays', how='left')
df_fao

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million),Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),Production viande volaille (1000 t),Dispo intérieure viande volaille (1000 t),PIB/hab ($ PPA internationaux constants de 2021),Pop rurale (pour 1000),Pop urbaine (pour 1000),Pop totale (pour 1000),Indice stabilité politique,TCAM PIB 2017-2022
0,Afrique du Sud,710,2017,35.0,36.71,514.0,1665.0,2115.0,14591.0,19369.002,37348.154,57635.162,-0.28,-0.816709
1,Afrique du Sud,710,2018,35.3,38.02,515.0,1762.0,2228.0,14571.0,19311.652,38086.769,58613.000,-0.24,-0.816709
2,Afrique du Sud,710,2019,35.9,37.72,488.0,1816.0,2247.0,14370.0,19244.858,38820.239,59587.885,-0.28,-0.816709
3,Afrique du Sud,710,2020,37.4,37.32,425.0,1887.0,2260.0,13267.0,19170.340,39550.889,60562.381,-0.25,-0.816709
4,Afrique du Sud,710,2021,37.6,36.41,372.0,1917.0,2239.0,13711.0,19088.162,40277.814,61502.603,-0.75,-0.816709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,Éthiopie,231,2018,65.8,0.62,0.0,74.0,70.0,2311.0,85207.113,22327.769,112664.152,-1.27,2.574930
879,Éthiopie,231,2019,66.4,0.48,1.0,58.0,56.0,2438.0,86759.295,23376.340,115737.383,-1.30,2.574930
880,Éthiopie,231,2020,67.9,0.54,0.0,68.0,64.0,2517.0,88295.647,24463.423,118917.671,-1.75,2.574930
881,Éthiopie,231,2021,70.8,0.40,1.0,49.0,48.0,2588.0,89813.744,25589.582,122138.588,-2.18,2.574930
882,Éthiopie,231,2022,71.6,0.45,0.0,56.0,56.0,2656.0,91310.183,26755.042,125384.287,-2.07,2.574930

## 4.2 - FAO : Taux de croissance annuel moyen de la population entre 2017 et 2022

In [ ]:
#Tableau temporaire
df_pivot_pop = df_fao.pivot_table(index='Pays',columns='Année',values='Pop totale (pour 1000)')

#Calcul du TCAM entre 2017 et 2022 : ((V_finale / V_initiale)^(1/n) - 1) * 100
n = 7
df_pivot_pop['TCAM Population 2017-2022'] = ((df_pivot_pop[2022] / df_pivot_pop[2017])**(1/n) - 1) * 100

#Ajout à df_fao
df_fao = pd.merge(df_fao,df_pivot_pop[['TCAM Population 2017-2022']], on='Pays', how='left')
df_fao

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million),Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),Production viande volaille (1000 t),Dispo intérieure viande volaille (1000 t),PIB/hab ($ PPA internationaux constants de 2021),Pop rurale (pour 1000),Pop urbaine (pour 1000),Pop totale (pour 1000),Indice stabilité politique,TCAM PIB 2017-2022,TCAM Population 2017-2022
0,Afrique du Sud,710,2017,35.0,36.71,514.0,1665.0,2115.0,14591.0,19369.002,37348.154,57635.162,-0.28,-0.816709,1.136212
1,Afrique du Sud,710,2018,35.3,38.02,515.0,1762.0,2228.0,14571.0,19311.652,38086.769,58613.000,-0.24,-0.816709,1.136212
2,Afrique du Sud,710,2019,35.9,37.72,488.0,1816.0,2247.0,14370.0,19244.858,38820.239,59587.885,-0.28,-0.816709,1.136212
3,Afrique du Sud,710,2020,37.4,37.32,425.0,1887.0,2260.0,13267.0,19170.340,39550.889,60562.381,-0.25,-0.816709,1.136212
4,Afrique du Sud,710,2021,37.6,36.41,372.0,1917.0,2239.0,13711.0,19088.162,40277.814,61502.603,-0.75,-0.816709,1.136212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,Éthiopie,231,2018,65.8,0.62,0.0,74.0,70.0,2311.0,85207.113,22327.769,112664.152,-1.27,2.574930,1.931845
879,Éthiopie,231,2019,66.4,0.48,1.0,58.0,56.0,2438.0,86759.295,23376.340,115737.383,-1.30,2.574930,1.931845
880,Éthiopie,231,2020,67.9,0.54,0.0,68.0,64.0,2517.0,88295.647,24463.423,118917.671,-1.75,2.574930,1.931845
881,Éthiopie,231,2021,70.8,0.40,1.0,49.0,48.0,2588.0,89813.744,25589.582,122138.588,-2.18,2.574930,1.931845
882,Éthiopie,231,2022,71.6,0.45,0.0,56.0,56.0,2656.0,91310.183,26755.042,125384.287,-2.07,2.574930,1.931845

## 4.3 - FAO : Taux d'urbanisation annuel

In [ ]:
df_fao['Taux urbanisation annuel'] = (df_fao['Pop urbaine (pour 1000)'] / df_fao['Pop totale (pour 1000)']) * 100
df_fao = df_fao.drop(columns=['Pop urbaine (pour 1000)','Pop rurale (pour 1000)'])
df_fao

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million),Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),Production viande volaille (1000 t),Dispo intérieure viande volaille (1000 t),PIB/hab ($ PPA internationaux constants de 2021),Pop totale (pour 1000),Indice stabilité politique,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation annuel
0,Afrique du Sud,710,2017,35.0,36.71,514.0,1665.0,2115.0,14591.0,57635.162,-0.28,-0.816709,1.136212,64.800987
1,Afrique du Sud,710,2018,35.3,38.02,515.0,1762.0,2228.0,14571.0,58613.000,-0.24,-0.816709,1.136212,64.980071
2,Afrique du Sud,710,2019,35.9,37.72,488.0,1816.0,2247.0,14370.0,59587.885,-0.28,-0.816709,1.136212,65.147872
3,Afrique du Sud,710,2020,37.4,37.32,425.0,1887.0,2260.0,13267.0,60562.381,-0.25,-0.816709,1.136212,65.306034
4,Afrique du Sud,710,2021,37.6,36.41,372.0,1917.0,2239.0,13711.0,61502.603,-0.75,-0.816709,1.136212,65.489609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,Éthiopie,231,2018,65.8,0.62,0.0,74.0,70.0,2311.0,112664.152,-1.27,2.574930,1.931845,19.817989
879,Éthiopie,231,2019,66.4,0.48,1.0,58.0,56.0,2438.0,115737.383,-1.30,2.574930,1.931845,20.197744
880,Éthiopie,231,2020,67.9,0.54,0.0,68.0,64.0,2517.0,118917.671,-1.75,2.574930,1.931845,20.571731
881,Éthiopie,231,2021,70.8,0.40,1.0,49.0,48.0,2588.0,122138.588,-2.18,2.574930,1.931845,20.951267
882,Éthiopie,231,2022,71.6,0.45,0.0,56.0,56.0,2656.0,125384.287,-2.07,2.574930,1.931845,21.338433

## 4.4 - FAO : Taux d'autosuffisance

In [ ]:
df_fao['Taux autosuffisance'] = (df_fao['Production viande volaille (1000 t)']/df_fao['Dispo intérieure viande volaille (1000 t)']) * 100
df_fao = df_fao.drop(columns=['Production viande volaille (1000 t)','Dispo intérieure viande volaille (1000 t)'])
df_fao

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million),Dispo viande volaille (kg/personne/an),Import viande volaille (1000 t),PIB/hab ($ PPA internationaux constants de 2021),Pop totale (pour 1000),Indice stabilité politique,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation annuel,Taux autosuffisance
0,Afrique du Sud,710,2017,35.0,36.71,514.0,14591.0,57635.162,-0.28,-0.816709,1.136212,64.800987,78.723404
1,Afrique du Sud,710,2018,35.3,38.02,515.0,14571.0,58613.000,-0.24,-0.816709,1.136212,64.980071,79.084381
2,Afrique du Sud,710,2019,35.9,37.72,488.0,14370.0,59587.885,-0.28,-0.816709,1.136212,65.147872,80.818870
3,Afrique du Sud,710,2020,37.4,37.32,425.0,13267.0,60562.381,-0.25,-0.816709,1.136212,65.306034,83.495575
4,Afrique du Sud,710,2021,37.6,36.41,372.0,13711.0,61502.603,-0.75,-0.816709,1.136212,65.489609,85.618580
...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,Éthiopie,231,2018,65.8,0.62,0.0,2311.0,112664.152,-1.27,2.574930,1.931845,19.817989,105.714286
879,Éthiopie,231,2019,66.4,0.48,1.0,2438.0,115737.383,-1.30,2.574930,1.931845,20.197744,103.571429
880,Éthiopie,231,2020,67.9,0.54,0.0,2517.0,118917.671,-1.75,2.574930,1.931845,20.571731,106.250000
881,Éthiopie,231,2021,70.8,0.40,1.0,2588.0,122138.588,-2.18,2.574930,1.931845,20.951267,102.083333
882,Éthiopie,231,2022,71.6,0.45,0.0,2656.0,125384.287,-2.07,2.574930,1.931845,21.338433,100.000000

## 4.5 - CEPII : Score langue

In [ ]:
#Création d'une fonction personnalisée à appliquer à chaque ligne
def score_langue(row):
#Création d'une liste des langues pour par ligne
    langues = [str(row['langoff_1']).lower(),
               str(row['langoff_2']).lower(),
               str(row['langoff_3']).lower()]

    # Condition 1 : français présent
    if any("français" in l or "french" in l for l in langues):
        return 2
    # Condition 2 : anglais présent (et donc pas français d'après l'ordre du IF)
    elif any("anglais" in l or "english" in l for l in langues):
        return 1
    # Condition 3 : Reste
    else:
        return 0

# Application de la fonction à df_fao
df_cepii['Score Langue'] = df_cepii.apply(score_langue, axis=1)
df_cepii

,Id pays,Distance avec la France (km),Code pays,Pays,Continent,langoff_1,langoff_2,langoff_3,Score Langue
0,ABW,"7716,752",533,Aruba,America,Dutch,Spanish,,0
1,AFG,"5500,665",4,Afghanistan,Asia,Persian,,,0
2,AGO,"6384,805",24,Angola,Africa,Portuguese,,,0
3,AIA,"6743,427",660,Anguilla,America,English,,,1
4,ALB,"1499,451",8,Albanie,Europe,Albanian,,,0
...,...,...,...,...,...,...,...,...,...
219,YUG,"1429,045",891,Serbie et Monténégro (ex-Yougoslavie),Europe,Serbo-Croatian,,,0
220,ZAF,"8769,679",711,Afrique du Sud,Africa,English,,,1
221,ZAR,"6036,588",180,Congo. Rép. dém. du,Africa,French,,,2
222,ZMB,"7236,737",894,Zambie,Africa,English,,,1
223,ZWE,"7771,569",716,Zimbabwe,Africa,English,,,1

# Etape 5 - Dataframe final

## 5.1 - Finalisation de df_fao

In [ ]:
#Conservation uniquement de l'année 2022 et suppression des lignes vides
df_fao_2022 = df_fao[df_fao['Année'] == 2022].reset_index(drop=True)
df_fao_2022 = df_fao_2022.rename(columns={'Pop sans moyen de se nourrir sainement (en million)':'Pop sans moyen de se nourrir sainement (en million) en 2022',
                                          'Dispo viande volaille (kg/personne/an)':'Dispo viande volaille (kg/personne/an) en 2022',
                                          'Import viande volaille (1000 t)':'Import viande volaille (1000 t) en 2022',
                                          'PIB/hab ($ PPA internationaux constants de 2021)':'PIB/hab ($ PPA internationaux constants de 2021) en 2022',
                                          'Pop totale (pour 1000)':'Pop totale (pour 1000) en 2022',
                                          'Indice stabilité politique':'Indice stabilité politique en 2022',
                                          'Taux urbanisation annuel':'Taux urbanisation 2022',
                                          'Taux autosuffisance':'Taux autosuffisance 2022'})
df_fao_2022 = df_fao_2022.dropna()
df_fao_2022

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022
0,Afrique du Sud,710,2022,38.1,35.47,304.0,13777.0,62378.410,-0.68,-0.816709,1.136212,65.725327,88.477180
1,Albanie,8,2022,0.3,22.68,47.0,17112.0,2827.608,0.11,2.747231,-0.351854,66.482801,28.125000
2,Algérie,12,2022,9.3,9.71,0.0,14782.0,45477.389,-0.65,-0.609191,1.250190,73.303931,100.226244
3,Allemagne,276,2022,1.7,16.63,789.0,62932.0,84086.227,0.63,0.215223,0.167996,76.268059,101.617251
4,Angola,24,2022,25.1,10.46,316.0,7398.0,35635.029,-0.63,-2.826024,2.375406,66.845073,15.281501
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Égypte,818,2022,49.6,17.90,20.0,16360.0,112618.250,-0.98,2.231638,1.186118,40.600996,99.156746
145,Émirats arabes unis,784,2022,0.2,47.53,638.0,68868.0,10242.086,0.74,-0.000830,1.490681,86.002178,6.241700
146,Équateur,218,2022,4.6,29.10,1.0,14187.0,17823.897,-0.37,0.008058,0.883504,64.482200,99.807322
147,États-Unis d'Amérique,840,2022,16.2,53.75,191.0,72679.0,341534.045,0.01,1.352448,0.396443,81.774258,121.208163
148,Éthiopie,231,2022,71.6,0.45,0.0,2656.0,125384.287,-2.07,2.574930,1.931845,21.338433,100.000000

In [ ]:
#Suppression de la ligne France
df_fao_2022 = df_fao_2022[df_fao_2022['Pays'] != 'France']

## 5.2 - Liaison df_fao avec df_cepii

In [ ]:
#Liaisons et identification des erreurs
df_f1 = pd.merge(df_fao_2022,df_cepii[['Code pays','Distance avec la France (km)','Continent','Score Langue']],on='Code pays',how='left')
df_f1.loc[df_f1['Distance avec la France (km)'].isnull()]

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Distance avec la France (km),Continent,Score Langue
0,Afrique du Sud,710,2022,38.1,35.47,304.0,13777.0,62378.410,-0.68,-0.816709,1.136212,65.725327,88.477180,NaN,NaN,NaN
14,Belgique,56,2022,0.1,16.30,309.0,62744.0,11641.820,0.58,0.991980,0.329783,98.739510,189.075630,NaN,NaN,NaN
55,Inde,356,2022,672.5,3.53,0.0,8594.0,1425423.212,-0.62,2.304702,0.677082,35.519617,100.079444,NaN,NaN,NaN
62,Italie,380,2022,4.0,20.25,142.0,52333.0,59619.115,0.47,0.989048,-0.183439,70.838042,100.000000,NaN,NaN,NaN
85,Monténégro,499,2022,0.1,21.67,11.0,25429.0,614.648,-0.14,1.609454,-0.126400,69.773269,15.384615,NaN,NaN,NaN
92,Norvège,578,2022,0.1,21.36,4.0,91051.0,5456.801,0.86,0.620262,0.480328,85.115363,97.457627,NaN,NaN,NaN
119,Serbie,688,2022,0.6,12.18,23.0,24633.0,6791.213,-0.17,3.441570,-0.580123,72.370459,88.549618,NaN,NaN,NaN
125,Suisse,756,2022,0.1,17.90,49.0,82777.0,8792.182,1.16,0.921865,0.562537,74.069429,71.337580,NaN,NaN,NaN
142,États-Unis d'Amérique,840,2022,16.2,53.75,191.0,72679.0,341534.045,0.01,1.352448,0.396443,81.774258,121.208163,NaN,NaN,NaN

In [ ]:
#Correction des clés
df_cepii.loc[df_cepii['Pays'] == 'Inde', 'Code pays'] = 356
df_cepii.loc[df_cepii['Pays'] == "Etats-Unis d'Amérique", 'Code pays'] = 840
df_cepii.loc[df_cepii['Pays'] == 'Afrique du Sud', 'Code pays'] = 710
df_cepii.loc[df_cepii['Pays'] == 'Italie', 'Code pays'] = 380
df_cepii.loc[df_cepii['Pays'] == 'Belgique et Luxembourg', 'Code pays'] = 56
df_cepii.loc[df_cepii['Pays'] == 'Suisse', 'Code pays'] = 756
df_cepii.loc[df_cepii['Pays'] == 'Serbie et Monténégro (ex-Yougoslavie)', 'Code pays'] = 688
df_cepii.loc[df_cepii['Pays'] == 'Norvège', 'Code pays'] = 578
df_fao_2022.loc[df_fao_2022['Pays'] == 'Monténégro', 'Code pays'] = 688

In [ ]:
#Liaison finale
df_f1 = pd.merge(df_fao_2022,df_cepii[['Id pays','Code pays','Continent','Distance avec la France (km)','Score Langue']],on='Code pays',how='left')
df_f1

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Id pays,Continent,Distance avec la France (km),Score Langue
0,Afrique du Sud,710,2022,38.1,35.47,304.0,13777.0,62378.410,-0.68,-0.816709,1.136212,65.725327,88.477180,ZAF,Africa,"8769,679",1
1,Albanie,8,2022,0.3,22.68,47.0,17112.0,2827.608,0.11,2.747231,-0.351854,66.482801,28.125000,ALB,Europe,"1499,451",0
2,Algérie,12,2022,9.3,9.71,0.0,14782.0,45477.389,-0.65,-0.609191,1.250190,73.303931,100.226244,DZA,Africa,"1233,811",2
3,Allemagne,276,2022,1.7,16.63,789.0,62932.0,84086.227,0.63,0.215223,0.167996,76.268059,101.617251,DEU,Europe,"789,5815",0
4,Angola,24,2022,25.1,10.46,316.0,7398.0,35635.029,-0.63,-2.826024,2.375406,66.845073,15.281501,AGO,Africa,"6384,805",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,Égypte,818,2022,49.6,17.90,20.0,16360.0,112618.250,-0.98,2.231638,1.186118,40.600996,99.156746,EGY,Africa,"3052,494",0
140,Émirats arabes unis,784,2022,0.2,47.53,638.0,68868.0,10242.086,0.74,-0.000830,1.490681,86.002178,6.241700,ARE,Asia,"5180,43",0
141,Équateur,218,2022,4.6,29.10,1.0,14187.0,17823.897,-0.37,0.008058,0.883504,64.482200,99.807322,ECU,America,"9561,102",0
142,États-Unis d'Amérique,840,2022,16.2,53.75,191.0,72679.0,341534.045,0.01,1.352448,0.396443,81.774258,121.208163,USA,America,"7456,767",1
143,Éthiopie,231,2022,71.6,0.45,0.0,2656.0,125384.287,-2.07,2.574930,1.931845,21.338433,100.000000,ETH,Africa,"5368,907",1

In [ ]:
#Caractéristiques
df_f1.info()
print("\n")
df_f1.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 17 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Pays                                                         144 non-null    object
 1   Code pays                                                    144 non-null    int64
 2   Année                                                        144 non-null    int64
 3   Pop sans moyen de se nourrir sainement (en million) en 2022  144 non-null    float64
 4   Dispo viande volaille (kg/personne/an) en 2022               144 non-null    float64
 5   Import viande volaille (1000 t) en 2022                      144 non-null    float64
 6   PIB/hab ($ PPA internationaux constants de 2021) en 2022     144 non-null    float64
 7   Pop totale (pour 1000) en 2022                               144 non-null    float64
 8   Indice stabilité politique en 2022                           144 non-null    float64
 9   TCAM PIB 2017-2022                                           144 non-null    float64
 10  TCAM Population 2017-2022                                    144 non-null    float64
 11  Taux urbanisation 2022                                       144 non-null    float64
 12  Taux autosuffisance 2022                                     144 non-null    float64
 13  Id pays                                                      144 non-null    object
 14  Continent                                                    144 non-null    object
 15  Distance avec la France (km)                                 144 non-null    object
 16  Score Langue                                                 144 non-null    int64
dtypes: float64(10), int64(3), object(4)
memory usage: 19.3+ KB

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Id pays,Continent,Distance avec la France (km),Score Langue
count,144,144.000000,144.0,144.000000,144.000000,144.000000,144.000000,1.440000e+02,144.000000,144.000000,144.000000,144.000000,144.000000,144,144,144,144.000000
unique,144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143,5,143,NaN
top,Afrique du Sud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YUG,Africa,"1429,045",NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,41,2,NaN
mean,NaN,433.229167,2022.0,15.649306,24.063403,90.659722,26157.187500,4.136114e+04,-0.074444,0.956009,0.802287,61.104380,76.677866,NaN,NaN,NaN,0.590278
std,NaN,249.534216,0.0,60.805216,17.975380,180.705655,24432.708388,1.282849e+05,0.846730,1.927474,0.784833,21.310158,43.933998,NaN,NaN,NaN,0.751811
min,NaN,8.000000,2022.0,0.000000,0.450000,0.000000,1386.000000,4.670900e+01,-2.780000,-4.747169,-0.992988,17.334204,0.000000,NaN,NaN,NaN,0.000000
25%,NaN,217.000000,2022.0,0.200000,9.652500,4.000000,6661.250000,3.002404e+03,-0.597500,0.070160,0.241148,44.934968,49.107143,NaN,NaN,NaN,0.000000
50%,NaN,424.000000,2022.0,1.450000,21.305000,22.000000,18172.500000,1.044047e+04,-0.020000,0.937754,0.751593,61.920792,88.513399,NaN,NaN,NaN,0.000000
75%,NaN,659.750000,2022.0,10.050000,34.382500,91.500000,39478.500000,3.475636e+04,0.635000,1.685255,1.404047,78.537638,100.000000,NaN,NaN,NaN,1.000000
max,NaN,894.000000,2022.0,672.500000,95.470000,1158.000000,132574.000000,1.425423e+06,1.320000,16.401932,2.403159,102.375342,222.603550,NaN,NaN,NaN,2.000000

## 5-3 - Liaison df_f1 avec df_wbg

In [ ]:
df_wbg_2018

,Id pays,Pays,Temp surface terrestre 2018 (°C),Taux pop accès électricité 2018,Indice perf log 2018,Indice corruption 2018,Indice état de droit 2018
0,AFG,Afghanistan,30.1259055,93.4,1.95,-1.50287592411041,-1.68912386894226
1,AGO,Angola,30.0623632,45.3,2.05,-1.19948387145996,-1.00106203556061
2,ALB,Albania,19.6873912,100,2.66,-0.546018898487091,-0.414752036333084
3,ARE,United Arab Emirates,43.6890475,100,3.96,1.11705148220062,0.774245142936707
4,ARG,Argentina,24.8753089,100,2.89,-0.0992739275097847,-0.219330430030823
...,...,...,...,...,...,...,...
152,VNM,Viet Nam,27.8129576,100,3.27,-0.511843025684357,-0.0354671441018581
153,YEM,"Yemen, Rep.",40.3114994,62,2.27,-1.65839195251465,-1.80602633953094
154,ZAF,South Africa,30.3751191,84.7,3.38,-0.136797428131104,-0.22182808816433
155,ZMB,Zambia,30.5621355,40.2,2.53,-0.678888440132141,-0.358306616544724
156,ZWE,Zimbabwe,32.6869318,45.4,2.12,-1.24637961387634,-1.29305863380432

In [ ]:
#Correction de certains codes
df_f1.loc[df_f1['Pays'] == 'République démocratique du Congo', 'Id pays'] = 'COD'
df_f1.loc[df_f1['Pays'] == 'Romanie', 'Id pays'] = 'ROU'
df_f1.loc[df_f1['Pays'] == 'Serbie', 'Id pays'] = 'SRB'
df_f1.loc[df_f1['Pays'] == 'Monténégro', 'Id pays'] = 'MNE'

#Liaisons
df_f2 = pd.merge(df_f1,df_wbg_2018[['Id pays','Temp surface terrestre 2018 (°C)','Taux pop accès électricité 2018','Indice perf log 2018','Indice corruption 2018','Indice état de droit 2018']],on='Id pays',how='left')
df_f2 = df_f2.dropna()
df_f2

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Id pays,Continent,Distance avec la France (km),Score Langue,Temp surface terrestre 2018 (°C),Taux pop accès électricité 2018,Indice perf log 2018,Indice corruption 2018,Indice état de droit 2018
0,Afrique du Sud,710,2022,38.1,35.47,304.0,13777.0,62378.410,-0.68,-0.816709,1.136212,65.725327,88.477180,ZAF,Africa,"8769,679",1,30.3751191,84.7,3.38,-0.136797428131104,-0.22182808816433
1,Albanie,8,2022,0.3,22.68,47.0,17112.0,2827.608,0.11,2.747231,-0.351854,66.482801,28.125000,ALB,Europe,"1499,451",0,19.6873912,100,2.66,-0.546018898487091,-0.414752036333084
2,Algérie,12,2022,9.3,9.71,0.0,14782.0,45477.389,-0.65,-0.609191,1.250190,73.303931,100.226244,DZA,Africa,"1233,811",2,37.874857,99.6,2.45,-0.658903956413269,-0.806978523731232
3,Allemagne,276,2022,1.7,16.63,789.0,62932.0,84086.227,0.63,0.215223,0.167996,76.268059,101.617251,DEU,Europe,"789,5815",0,16.6872467,100,4.2,1.89839863777161,1.59137535095215
4,Angola,24,2022,25.1,10.46,316.0,7398.0,35635.029,-0.63,-2.826024,2.375406,66.845073,15.281501,AGO,Africa,"6384,805",0,30.0623632,45.3,2.05,-1.19948387145996,-1.00106203556061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Zimbabwe,716,2022,0.0,7.69,5.0,3323.0,16069.056,-0.89,-0.550834,1.170009,37.169738,95.161290,ZWE,Africa,"7771,569",1,32.6869318,45.4,2.12,-1.24637961387634,-1.29305863380432
139,Égypte,818,2022,49.6,17.90,20.0,16360.0,112618.250,-0.98,2.231638,1.186118,40.600996,99.156746,EGY,Africa,"3052,494",0,37.0626519,100,2.82,-0.514722347259521,-0.301445573568344
140,Émirats arabes unis,784,2022,0.2,47.53,638.0,68868.0,10242.086,0.74,-0.000830,1.490681,86.002178,6.241700,ARE,Asia,"5180,43",0,43.6890475,100,3.96,1.11705148220062,0.774245142936707
141,Équateur,218,2022,4.6,29.10,1.0,14187.0,17823.897,-0.37,0.008058,0.883504,64.482200,99.807322,ECU,America,"9561,102",0,27.128669,98.7,2.88,-0.629500389099121,-0.663264274597168
142,États-Unis d'Amérique,840,2022,16.2,53.75,191.0,72679.0,341534.045,0.01,1.352448,0.396443,81.774258,121.208163,USA,America,"7456,767",1,16.7533663,100,3.89,1.2927473783493,1.47568726539612

In [ ]:
#Caractéristiques
df_f2.info()
print("\n")
df_f2.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 125 entries, 0 to 142
Data columns (total 22 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Pays                                                         125 non-null    object
 1   Code pays                                                    125 non-null    int64
 2   Année                                                        125 non-null    int64
 3   Pop sans moyen de se nourrir sainement (en million) en 2022  125 non-null    float64
 4   Dispo viande volaille (kg/personne/an) en 2022               125 non-null    float64
 5   Import viande volaille (1000 t) en 2022                      125 non-null    float64
 6   PIB/hab ($ PPA internationaux constants de 2021) en 2022     125 non-null    float64
 7   Pop totale (pour 1000) en 2022                               125 non-null    float64
 8   Indice stabilité politique en 2022                           125 non-null    float64
 9   TCAM PIB 2017-2022                                           125 non-null    float64
 10  TCAM Population 2017-2022                                    125 non-null    float64
 11  Taux urbanisation 2022                                       125 non-null    float64
 12  Taux autosuffisance 2022                                     125 non-null    float64
 13  Id pays                                                      125 non-null    object
 14  Continent                                                    125 non-null    object
 15  Distance avec la France (km)                                 125 non-null    object
 16  Score Langue                                                 125 non-null    int64
 17  Temp surface terrestre 2018 (°C)                             125 non-null    object
 18  Taux pop accès électricité 2018                              125 non-null    object
 19  Indice perf log 2018                                         125 non-null    object
 20  Indice corruption 2018                                       125 non-null    object
 21  Indice état de droit 2018                                    125 non-null    object
dtypes: float64(10), int64(3), object(9)
memory usage: 22.5+ KB

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Id pays,Continent,Distance avec la France (km),Score Langue,Temp surface terrestre 2018 (°C),Taux pop accès électricité 2018,Indice perf log 2018,Indice corruption 2018,Indice état de droit 2018
count,125,125.000000,125.0,125.000000,125.000000,125.000000,125.000000,1.250000e+02,125.000000,125.000000,125.000000,125.000000,125.000000,125,125,125,125.000000,125,125,125,125,125
unique,125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125,5,124,NaN,125,55,97,125,125
top,Afrique du Sud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZAF,Europe,"1429,045",NaN,30.3751191,100,2.81,-0.136797428131104,-0.22182808816433
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,37,2,NaN,1,55,5,1,1
mean,NaN,431.424000,2022.0,16.698400,22.748800,98.952000,27253.400000,4.544669e+04,-0.127040,1.056946,0.805607,62.896039,81.302779,NaN,NaN,NaN,0.568000,NaN,NaN,NaN,NaN,NaN
std,NaN,246.252436,0.0,64.800911,16.019901,190.702092,25434.542588,1.367821e+05,0.830298,1.988015,0.776983,20.923538,42.745198,NaN,NaN,NaN,0.776011,NaN,NaN,NaN,NaN,NaN
min,NaN,8.000000,2022.0,0.000000,0.840000,0.000000,1386.000000,2.263050e+02,-2.780000,-4.747169,-0.992988,17.334204,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,218.000000,2022.0,0.300000,9.710000,4.000000,6353.000000,4.730226e+03,-0.630000,0.209541,0.329783,49.176196,64.719101,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,418.000000,2022.0,1.700000,20.740000,24.000000,18459.000000,1.150361e+04,-0.100000,0.986704,0.763461,65.725327,90.123457,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,643.000000,2022.0,10.200000,31.910000,98.000000,41071.000000,3.732906e+04,0.530000,1.764682,1.403079,80.748481,100.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN
max,NaN,894.000000,2022.0,672.500000,70.860000,1158.000000,132574.000000,1.425423e+06,1.320000,16.401932,2.403159,99.514949,222.603550,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN

## 5.4 - Identification des outliers

In [ ]:
df_num = df_f2.select_dtypes(include=[np.number])

mean = df_num.mean()
std = df_num.std()

z_scores = (df_num - mean) / std

seuil = 3
mask_outliers = (np.abs(z_scores) > seuil).any(axis=1)
outliers = df_f2[mask_outliers]

print(f"Nombre total de pays avec au moins une valeur aberrante (Z > {seuil}) : {len(outliers)}")
print("-" * 50)

outliers

Nombre total de pays avec au moins une valeur aberrante (Z > 3) : 11
--------------------------------------------------

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Id pays,Continent,Distance avec la France (km),Score Langue,Temp surface terrestre 2018 (°C),Taux pop accès électricité 2018,Indice perf log 2018,Indice corruption 2018,Indice état de droit 2018
3,Allemagne,276,2022,1.7,16.63,789.0,62932.0,84086.227,0.63,0.215223,0.167996,76.268059,101.617251,DEU,Europe,"789,5815",0,16.6872467,100,4.2,1.89839863777161,1.59137535095215
51,Guyana,328,2022,0.1,70.86,1.0,37068.0,821.637,0.02,16.401932,0.960086,26.282775,98.275862,GUY,America,"7310,159",1,26.0623534,90.9,2.36,-0.250006973743439,-0.38360184431076
55,Inde,356,2022,672.5,3.53,0.0,8594.0,1425423.212,-0.62,2.304702,0.677082,35.519617,100.079444,IND,Asia,"7073,011",1,32.7504196,95.7,3.18,-0.229758977890015,-0.00142208894249052
59,Irlande,372,2022,0.0,29.99,110.0,124489.0,5110.016,0.88,5.090169,0.867328,62.324952,91.428571,IRL,Europe,"1024,208",1,12.4677383,100,3.51,1.5349406003952,1.41250944137573
74,Luxembourg,442,2022,0.0,19.70,14.0,132574.0,653.313,1.06,0.043610,1.308277,87.054597,0.000000,LUX,Europe,"476,1561",2,16.9091626,100,3.63,2.04803919792175,1.76795589923859
83,Mexique,484,2022,28.4,38.49,1158.0,21392.0,128613.117,-0.69,-0.255149,0.592854,86.518479,76.767677,MEX,America,"9276,133",0,31.3753769,99.5,3.05,-0.949163556098938,-0.641221523284912
100,Pays-Bas (Royaume des),528,2022,0.2,13.52,897.0,71324.0,17904.421,0.73,1.187735,0.479045,89.634208,213.317191,NLD,Europe,"660,9895",0,16.467841,100,4.02,1.88914597034454,1.74446511268616
102,Pologne,616,2022,2.5,33.30,78.0,43405.0,38385.739,0.51,3.396804,0.048766,59.123877,209.541985,POL,Europe,"1352,006",0,15.937271,100,3.54,0.622786521911621,0.376929372549057
106,Royaume-Uni de Grande-Bretagne et d'Irlande du...,826,2022,1.7,35.62,947.0,52982.0,68179.315,0.53,0.378015,0.388325,84.246464,78.188976,GBR,Europe,"749,6503",1,13.3126673,100,3.99,1.80687081813812,1.60317921638489
108,République arabe syrienne,760,2022,12.3,5.14,22.0,4455.0,22462.173,-2.78,-1.573224,2.248308,51.725592,80.869565,SYR,Asia,"3130,229",0,33.0630895,86,2.3,-1.64825057983398,-2.05464148521423
131,Thaïlande,764,2022,12.9,10.72,2.0,20763.0,71735.329,-0.39,0.468258,0.115064,51.290281,222.603550,THA,Asia,"9475,635",0,30.4383369,99.8,3.41,-0.458226591348648,-0.00403118878602982

In [ ]:
#Identification des pays représentant 60% de la population et du top 100
df_f2 = df_f2.sort_values(by='Pop totale (pour 1000) en 2022', ascending=False).reset_index(drop=True)
df_f2['Pop cumulée (pour 1000) en 2022'] = df_f2['Pop totale (pour 1000) en 2022'].cumsum()
df_f2['Pop cumulée (%) en 2022'] = (df_f2['Pop cumulée (pour 1000) en 2022']*1000 / 8000000000) *100
df_60 = df_f2[df_f2['Pop cumulée (%) en 2022'] < 60]
df_60.shape

(35, 24)

Les 125 pays de l'échantillon représentent bien plus de 60% de la population mondiale.

# Etape 6 - Mise en forme du Dataframe final P11

## 6.1 - Nettoyage du dataframe final

In [ ]:
#Caractéristiques du df_f2
df_f2.info()
print("\n")
df_f2.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 24 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Pays                                                         125 non-null    object
 1   Code pays                                                    125 non-null    int64
 2   Année                                                        125 non-null    int64
 3   Pop sans moyen de se nourrir sainement (en million) en 2022  125 non-null    float64
 4   Dispo viande volaille (kg/personne/an) en 2022               125 non-null    float64
 5   Import viande volaille (1000 t) en 2022                      125 non-null    float64
 6   PIB/hab ($ PPA internationaux constants de 2021) en 2022     125 non-null    float64
 7   Pop totale (pour 1000) en 2022                               125 non-null    float64
 8   Indice stabilité politique en 2022                           125 non-null    float64
 9   TCAM PIB 2017-2022                                           125 non-null    float64
 10  TCAM Population 2017-2022                                    125 non-null    float64
 11  Taux urbanisation 2022                                       125 non-null    float64
 12  Taux autosuffisance 2022                                     125 non-null    float64
 13  Id pays                                                      125 non-null    object
 14  Continent                                                    125 non-null    object
 15  Distance avec la France (km)                                 125 non-null    object
 16  Score Langue                                                 125 non-null    int64
 17  Temp surface terrestre 2018 (°C)                             125 non-null    object
 18  Taux pop accès électricité 2018                              125 non-null    object
 19  Indice perf log 2018                                         125 non-null    object
 20  Indice corruption 2018                                       125 non-null    object
 21  Indice état de droit 2018                                    125 non-null    object
 22  Pop cumulée (pour 1000) en 2022                              125 non-null    float64
 23  Pop cumulée (%) en 2022                                      125 non-null    float64
dtypes: float64(12), int64(3), object(9)
memory usage: 23.6+ KB

,Pays,Code pays,Année,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Id pays,Continent,Distance avec la France (km),Score Langue,Temp surface terrestre 2018 (°C),Taux pop accès électricité 2018,Indice perf log 2018,Indice corruption 2018,Indice état de droit 2018,Pop cumulée (pour 1000) en 2022,Pop cumulée (%) en 2022
count,125,125.000000,125.0,125.000000,125.000000,125.000000,125.000000,1.250000e+02,125.000000,125.000000,125.000000,125.000000,125.000000,125,125,125,125.000000,125,125,125,125,125,1.250000e+02,125.000000
unique,125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125,5,124,NaN,125,55,97,125,125,NaN,NaN
top,Inde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IND,Europe,"1429,045",NaN,32.7504196,100,2.81,-0.229758977890015,-0.00142208894249052,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,37,2,NaN,1,55,5,1,1,NaN,NaN
mean,NaN,431.424000,2022.0,16.698400,22.748800,98.952000,27253.400000,4.544669e+04,-0.127040,1.056946,0.805607,62.896039,81.302779,NaN,NaN,NaN,0.568000,NaN,NaN,NaN,NaN,NaN,4.968965e+06,62.112057
std,NaN,246.252436,0.0,64.800911,16.019901,190.702092,25434.542588,1.367821e+05,0.830298,1.988015,0.776983,20.923538,42.745198,NaN,NaN,NaN,0.776011,NaN,NaN,NaN,NaN,NaN,9.335849e+05,11.669811
min,NaN,8.000000,2022.0,0.000000,0.840000,0.000000,1386.000000,2.263050e+02,-2.780000,-4.747169,-0.992988,17.334204,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.425423e+06,17.817790
25%,NaN,218.000000,2022.0,0.300000,9.710000,4.000000,6353.000000,4.730226e+03,-0.630000,0.209541,0.329783,49.176196,64.719101,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,4.673928e+06,58.424096
50%,NaN,418.000000,2022.0,1.700000,20.740000,24.000000,18459.000000,1.150361e+04,-0.100000,0.986704,0.763461,65.725327,90.123457,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,5.375352e+06,67.191903
75%,NaN,643.000000,2022.0,10.200000,31.910000,98.000000,41071.000000,3.732906e+04,0.530000,1.764682,1.403079,80.748481,100.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,5.617428e+06,70.217852
max,NaN,894.000000,2022.0,672.500000,70.860000,1158.000000,132574.000000,1.425423e+06,1.320000,16.401932,2.403159,99.514949,222.603550,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,5.680836e+06,71.010453

In [ ]:
#Suppression des colonnes superflues
df_f3= df_f2.drop(columns=['Code pays','Année','Id pays','Pop cumulée (pour 1000) en 2022','Pop cumulée (%) en 2022'])

#Convertir 'Distance avec la France (km)' en nombres en remplaçant les ',' par des '.'
df_f3['Distance avec la France (km)'] = df_f3['Distance avec la France (km)'].str.replace(',', '.').astype(float)

#Convertir le type des autres variables devant être des nombres
df_f3['Temp surface terrestre 2018 (°C)'] = df_f3['Temp surface terrestre 2018 (°C)'].astype(float)
df_f3['Taux pop accès électricité 2018'] = df_f3['Taux pop accès électricité 2018'].astype(float)
df_f3['Indice perf log 2018'] = df_f3['Indice perf log 2018'].astype(float)
df_f3['Indice corruption 2018'] = df_f3['Indice corruption 2018'].astype(float)
df_f3['Indice état de droit 2018'] = df_f3['Indice état de droit 2018'].astype(float)

## 6.2 - Identification des outliers

In [ ]:
#Identification
noms_pays = df_f3['Pays'].values
df_num = df_f3.select_dtypes(include=[np.number])

mean = df_num.mean()
std = df_num.std()

z_scores = (df_num - mean) / std

anomalies = []

for i in range(len(z_scores)):
    row = z_scores.iloc[i]
    for column, value in row.items():
        if abs(value) > 5:
            anomalies.append({
                'Pays': noms_pays[i],
                'Variable': column,
                'Valeur Brute': df_num.iloc[i][column],
                'Z-score': round(value, 2)
            })

df_anomalies_detail = pd.DataFrame(anomalies)

df_anomalies_detail.sort_values(by='Z-score', ascending=False)

,Pays,Variable,Valeur Brute,Z-score
0,Inde,Pop sans moyen de se nourrir sainement (en mil...,6.725000e+02,10.12
1,Inde,Pop totale (pour 1000) en 2022,1.425423e+06,10.09
3,Guyana,TCAM PIB 2017-2022,1.640193e+01,7.72
2,Mexique,Import viande volaille (1000 t) en 2022,1.158000e+03,5.55

Nous conservons le Mexiques car la variable 'Import viande volaille (1000 t) en 2022' est stratégique pour l'analyse business.

Nous supprimons l'Inde car elle aura une trop forte influence sur l'étude du marché et donc la fausser, de plus une variable 'Pop sans moyen de se nourrir sainement' trop élevée n'est pas un bon indicateur pour notre business.

Nous supprimons également le Guyana car la croissance exceptionnelle de son PIB est déconnecté du secteur alimentaire car il s'agit de l'exploitation pétrolière, cela fausserait notre analyse.

In [ ]:
#Suppression des outliers
pays_a_supprimer = ['Inde', 'Guyana']
df_P11 = df_f3[~df_f3['Pays'].isin(pays_a_supprimer)]
df_P11.reset_index(drop=True, inplace=True)

## 6.3 - Finalisation et extraction du dataframe final

In [ ]:
#Caractéristiques
df_P11.info()
print("\n")
df_P11.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 19 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Pays                                                         123 non-null    object
 1   Pop sans moyen de se nourrir sainement (en million) en 2022  123 non-null    float64
 2   Dispo viande volaille (kg/personne/an) en 2022               123 non-null    float64
 3   Import viande volaille (1000 t) en 2022                      123 non-null    float64
 4   PIB/hab ($ PPA internationaux constants de 2021) en 2022     123 non-null    float64
 5   Pop totale (pour 1000) en 2022                               123 non-null    float64
 6   Indice stabilité politique en 2022                           123 non-null    float64
 7   TCAM PIB 2017-2022                                           123 non-null    float64
 8   TCAM Population 2017-2022                                    123 non-null    float64
 9   Taux urbanisation 2022                                       123 non-null    float64
 10  Taux autosuffisance 2022                                     123 non-null    float64
 11  Continent                                                    123 non-null    object
 12  Distance avec la France (km)                                 123 non-null    float64
 13  Score Langue                                                 123 non-null    int64
 14  Temp surface terrestre 2018 (°C)                             123 non-null    float64
 15  Taux pop accès électricité 2018                              123 non-null    float64
 16  Indice perf log 2018                                         123 non-null    float64
 17  Indice corruption 2018                                       123 non-null    float64
 18  Indice état de droit 2018                                    123 non-null    float64
dtypes: float64(16), int64(1), object(2)
memory usage: 18.4+ KB

,Pays,Pop sans moyen de se nourrir sainement (en million) en 2022,Dispo viande volaille (kg/personne/an) en 2022,Import viande volaille (1000 t) en 2022,PIB/hab ($ PPA internationaux constants de 2021) en 2022,Pop totale (pour 1000) en 2022,Indice stabilité politique en 2022,TCAM PIB 2017-2022,TCAM Population 2017-2022,Taux urbanisation 2022,Taux autosuffisance 2022,Continent,Distance avec la France (km),Score Langue,Temp surface terrestre 2018 (°C),Taux pop accès électricité 2018,Indice perf log 2018,Indice corruption 2018,Indice état de droit 2018
count,123,123.000000,123.000000,123.000000,123.000000,123.000000,123.000000,123.000000,123.000000,123.000000,123.000000,123,123.000000,123.000000,123.000000,123.000000,123.000000,123.000000,123.000000
unique,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,États-Unis d'Amérique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Europe,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,11.501626,22.513902,100.552846,27325.308943,34590.173967,-0.124228,0.922046,0.805396,63.416280,81.012131,NaN,5282.989287,0.560976,24.329792,86.502439,2.913415,-0.046098,-0.009245
std,NaN,26.707671,15.452779,191.838440,25570.930445,57197.790541,0.835775,1.433811,0.783115,20.677703,43.032184,NaN,3730.001223,0.780357,9.462774,23.986497,0.550654,0.995476,0.958742
min,NaN,0.000000,0.840000,0.000000,1386.000000,226.305000,-2.780000,-4.747169,-0.992988,17.334204,0.000000,NaN,473.730400,0.000000,-3.754938,14.400000,2.050000,-1.648251,-2.054641
25%,NaN,0.300000,9.845000,4.000000,6312.500000,4802.931500,-0.630000,0.181835,0.309897,49.823971,63.518971,NaN,1828.417500,0.000000,16.720306,86.450000,2.530000,-0.783857,-0.710148
50%,NaN,1.700000,20.740000,25.000000,18459.000000,11503.606000,-0.100000,0.986312,0.763461,66.482801,89.940828,NaN,4587.869000,0.000000,26.657709,99.800000,2.790000,-0.340440,-0.224594
75%,NaN,10.100000,31.610000,98.500000,42238.000000,36482.046500,0.555000,1.744704,1.405015,81.115223,100.000000,NaN,7879.909000,1.000000,30.406728,100.000000,3.275000,0.541407,0.640509
max,NaN,173.300000,70.330000,1158.000000,132574.000000,341534.045000,1.320000,5.090169,2.403159,99.514949,222.603550,NaN,18894.290000,2.000000,43.689048,100.000000,4.200000,2.171759,2.034399

In [ ]:
#Suppression des accents
df_P11.loc[:, 'Pays'] = (df_P11['Pays']
                         .str.normalize('NFKD')
                         .str.encode('ascii', 'ignore')
                         .str.decode('utf-8'))

In [ ]:
#Extraction en CSV
df_P11.to_csv("Data P11.csv", index=False)